.\"     Title: apt\-key
.\"    Author: Jason Gunthorpe
.\" Generator: DocBook XSL Stylesheets v1.71.0 <http://docbook.sf.net/>
.\"      Date: 14 December 2003
.\"    Manual: 
.\"    Source: Linux
.\"
.TH "APT\-KEY" "8" "14 December 2003" "Linux" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
apt\-key \- APT key management utility
.SH "SYNOPSIS"
.HP 8
\fBapt\-key\fR [\fIcommand\fR/] [\fB\fIarguments\fR\fR...]
.SH "DESCRIPTION"
.PP

\fBapt\-key\fR
is used to manage the list of keys used by apt to authenticate packages. Packages which have been authenticated using these keys will be considered trusted.
.SH "COMMANDS"
.PP
add \fIfilename\fR
.RS 3n
Add a new key to the list of trusted keys. The key is read from
\fIfilename\fR, or standard input if
\fIfilename\fR
is
\-.
.RE
.PP
del \fIkeyid\fR
.RS 3n
Remove a key from the list of trusted keys.
.RE
.PP
list
.RS 3n
List trusted keys.
.RE
.PP
update
.RS 3n
Update the local keyring with the keyring of Debian archive keys and removes from the keyring the archive keys which are no longer valid.
.RE
.SH "FILES"
.PP
\fI/etc/apt/trusted.gpg\fR
.RS 3n
Keyring of local trusted keys, new keys will be added here.
.RE
.PP
\fI/etc/apt/trustdb.gpg\fR
.RS 3n
Local trust database of archive keys.
.RE
.PP
\fI/usr/share/keyrings/debian\-archive\-keyring.gpg\fR
.RS 3n
Keyring of Debian archive trusted keys.
.RE
.PP
\fI/usr/share/keyrings/debian\-archive\-removed\-keys.gpg\fR
.RS 3n
Keyring of Debian archive removed trusted keys.
.RE
.SH "SEE ALSO"
.PP

\fBapt\-get\fR(8),
\fBapt\-secure\fR(8)
.SH "BUGS"
.PP
[1]\&\fIAPT bug page\fR. If you wish to report a bug in APT, please see
\fI/usr/share/doc/debian/bug\-reporting.txt\fR
or the
\fBreportbug\fR(1)
command.
.SH "AUTHOR"
.PP
APT was written by the APT team
<apt@packages.debian.org>.
.SH "AUTHOR"
.PP
\fBJason Gunthorpe\fR
.sp -1n
.IP "" 3n
Author.
.SH "COPYRIGHT"
Copyright \(co 1998\-2001 Jason Gunthorpe
.br
.SH "REFERENCES"
.TP 3
1.\ APT bug page
\%http://bugs.debian.org/src:apt
