#! /bin/sh

set -e

rem_sudoer ()
{
    line="$1"
    grep -v -F -q "$line" /etc/sudoers >/etc/sudoers.tmp
    mv /etc/sudoers.tmp /etc/sudoers.
}

## Remove the sudoer line

rem_sudoer 'user ALL = NOPASSWD: /usr/libexec/apt-worker'
