/* Generated by makegdkpixbufalias.pl */

#ifndef DISABLE_VISIBILITY

#include <glib.h>

#ifdef G_HAVE_GNUC_VISIBILITY

#ifdef  GDK_PIXBUF_DISABLE_DEPRECATED
#define WAS_NO_DEPR
#endif
#undef  GDK_PIXBUF_DISABLE_DEPRECATED

#ifdef  G_DISABLE_DEPRECATED
#define WAS_NO_G_DEPR
#endif
#undef  G_DISABLE_DEPRECATED

#include "gdk-pixbuf.h"
#include "gdk-pixdata.h"

extern __typeof (gdk_colorspace_get_type) IA__gdk_colorspace_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
extern __typeof (gdk_colorspace_get_type) gdk_colorspace_get_type __attribute((alias("IA__gdk_colorspace_get_type"), visibility("default")));
#define gdk_colorspace_get_type IA__gdk_colorspace_get_type

extern __typeof (gdk_interp_type_get_type) IA__gdk_interp_type_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
extern __typeof (gdk_interp_type_get_type) gdk_interp_type_get_type __attribute((alias("IA__gdk_interp_type_get_type"), visibility("default")));
#define gdk_interp_type_get_type IA__gdk_interp_type_get_type

extern __typeof (gdk_pixbuf_add_alpha) IA__gdk_pixbuf_add_alpha __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_add_alpha) gdk_pixbuf_add_alpha __attribute((alias("IA__gdk_pixbuf_add_alpha"), visibility("default")));
#define gdk_pixbuf_add_alpha IA__gdk_pixbuf_add_alpha

extern __typeof (gdk_pixbuf_alpha_mode_get_type) IA__gdk_pixbuf_alpha_mode_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
extern __typeof (gdk_pixbuf_alpha_mode_get_type) gdk_pixbuf_alpha_mode_get_type __attribute((alias("IA__gdk_pixbuf_alpha_mode_get_type"), visibility("default")));
#define gdk_pixbuf_alpha_mode_get_type IA__gdk_pixbuf_alpha_mode_get_type

extern __typeof (gdk_pixbuf_animation_get_height) IA__gdk_pixbuf_animation_get_height __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_animation_get_height) gdk_pixbuf_animation_get_height __attribute((alias("IA__gdk_pixbuf_animation_get_height"), visibility("default")));
#define gdk_pixbuf_animation_get_height IA__gdk_pixbuf_animation_get_height

extern __typeof (gdk_pixbuf_animation_get_iter) IA__gdk_pixbuf_animation_get_iter __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_animation_get_iter) gdk_pixbuf_animation_get_iter __attribute((alias("IA__gdk_pixbuf_animation_get_iter"), visibility("default")));
#define gdk_pixbuf_animation_get_iter IA__gdk_pixbuf_animation_get_iter

extern __typeof (gdk_pixbuf_animation_get_static_image) IA__gdk_pixbuf_animation_get_static_image __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_animation_get_static_image) gdk_pixbuf_animation_get_static_image __attribute((alias("IA__gdk_pixbuf_animation_get_static_image"), visibility("default")));
#define gdk_pixbuf_animation_get_static_image IA__gdk_pixbuf_animation_get_static_image

extern __typeof (gdk_pixbuf_animation_get_type) IA__gdk_pixbuf_animation_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
extern __typeof (gdk_pixbuf_animation_get_type) gdk_pixbuf_animation_get_type __attribute((alias("IA__gdk_pixbuf_animation_get_type"), visibility("default")));
#define gdk_pixbuf_animation_get_type IA__gdk_pixbuf_animation_get_type

extern __typeof (gdk_pixbuf_animation_get_width) IA__gdk_pixbuf_animation_get_width __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_animation_get_width) gdk_pixbuf_animation_get_width __attribute((alias("IA__gdk_pixbuf_animation_get_width"), visibility("default")));
#define gdk_pixbuf_animation_get_width IA__gdk_pixbuf_animation_get_width

extern __typeof (gdk_pixbuf_animation_is_static_image) IA__gdk_pixbuf_animation_is_static_image __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_animation_is_static_image) gdk_pixbuf_animation_is_static_image __attribute((alias("IA__gdk_pixbuf_animation_is_static_image"), visibility("default")));
#define gdk_pixbuf_animation_is_static_image IA__gdk_pixbuf_animation_is_static_image

extern __typeof (gdk_pixbuf_animation_iter_advance) IA__gdk_pixbuf_animation_iter_advance __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_animation_iter_advance) gdk_pixbuf_animation_iter_advance __attribute((alias("IA__gdk_pixbuf_animation_iter_advance"), visibility("default")));
#define gdk_pixbuf_animation_iter_advance IA__gdk_pixbuf_animation_iter_advance

extern __typeof (gdk_pixbuf_animation_iter_get_delay_time) IA__gdk_pixbuf_animation_iter_get_delay_time __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_animation_iter_get_delay_time) gdk_pixbuf_animation_iter_get_delay_time __attribute((alias("IA__gdk_pixbuf_animation_iter_get_delay_time"), visibility("default")));
#define gdk_pixbuf_animation_iter_get_delay_time IA__gdk_pixbuf_animation_iter_get_delay_time

extern __typeof (gdk_pixbuf_animation_iter_get_pixbuf) IA__gdk_pixbuf_animation_iter_get_pixbuf __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_animation_iter_get_pixbuf) gdk_pixbuf_animation_iter_get_pixbuf __attribute((alias("IA__gdk_pixbuf_animation_iter_get_pixbuf"), visibility("default")));
#define gdk_pixbuf_animation_iter_get_pixbuf IA__gdk_pixbuf_animation_iter_get_pixbuf

extern __typeof (gdk_pixbuf_animation_iter_get_type) IA__gdk_pixbuf_animation_iter_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
extern __typeof (gdk_pixbuf_animation_iter_get_type) gdk_pixbuf_animation_iter_get_type __attribute((alias("IA__gdk_pixbuf_animation_iter_get_type"), visibility("default")));
#define gdk_pixbuf_animation_iter_get_type IA__gdk_pixbuf_animation_iter_get_type

extern __typeof (gdk_pixbuf_animation_iter_on_currently_loading_frame) IA__gdk_pixbuf_animation_iter_on_currently_loading_frame __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_animation_iter_on_currently_loading_frame) gdk_pixbuf_animation_iter_on_currently_loading_frame __attribute((alias("IA__gdk_pixbuf_animation_iter_on_currently_loading_frame"), visibility("default")));
#define gdk_pixbuf_animation_iter_on_currently_loading_frame IA__gdk_pixbuf_animation_iter_on_currently_loading_frame

extern __typeof (gdk_pixbuf_animation_new_from_file) IA__gdk_pixbuf_animation_new_from_file __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_animation_new_from_file) gdk_pixbuf_animation_new_from_file __attribute((alias("IA__gdk_pixbuf_animation_new_from_file"), visibility("default")));
#define gdk_pixbuf_animation_new_from_file IA__gdk_pixbuf_animation_new_from_file

#ifdef G_OS_WIN32
extern __typeof (gdk_pixbuf_animation_new_from_file_utf8) IA__gdk_pixbuf_animation_new_from_file_utf8 __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_animation_new_from_file_utf8) gdk_pixbuf_animation_new_from_file_utf8 __attribute((alias("IA__gdk_pixbuf_animation_new_from_file_utf8"), visibility("default")));
#define gdk_pixbuf_animation_new_from_file_utf8 IA__gdk_pixbuf_animation_new_from_file_utf8

#endif
extern __typeof (gdk_pixbuf_animation_ref) IA__gdk_pixbuf_animation_ref __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_animation_ref) gdk_pixbuf_animation_ref __attribute((alias("IA__gdk_pixbuf_animation_ref"), visibility("default")));
#define gdk_pixbuf_animation_ref IA__gdk_pixbuf_animation_ref

extern __typeof (gdk_pixbuf_animation_unref) IA__gdk_pixbuf_animation_unref __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_animation_unref) gdk_pixbuf_animation_unref __attribute((alias("IA__gdk_pixbuf_animation_unref"), visibility("default")));
#define gdk_pixbuf_animation_unref IA__gdk_pixbuf_animation_unref

extern __typeof (gdk_pixbuf_composite) IA__gdk_pixbuf_composite __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_composite) gdk_pixbuf_composite __attribute((alias("IA__gdk_pixbuf_composite"), visibility("default")));
#define gdk_pixbuf_composite IA__gdk_pixbuf_composite

extern __typeof (gdk_pixbuf_composite_color) IA__gdk_pixbuf_composite_color __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_composite_color) gdk_pixbuf_composite_color __attribute((alias("IA__gdk_pixbuf_composite_color"), visibility("default")));
#define gdk_pixbuf_composite_color IA__gdk_pixbuf_composite_color

extern __typeof (gdk_pixbuf_composite_color_simple) IA__gdk_pixbuf_composite_color_simple __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_composite_color_simple) gdk_pixbuf_composite_color_simple __attribute((alias("IA__gdk_pixbuf_composite_color_simple"), visibility("default")));
#define gdk_pixbuf_composite_color_simple IA__gdk_pixbuf_composite_color_simple

extern __typeof (gdk_pixbuf_copy) IA__gdk_pixbuf_copy __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_copy) gdk_pixbuf_copy __attribute((alias("IA__gdk_pixbuf_copy"), visibility("default")));
#define gdk_pixbuf_copy IA__gdk_pixbuf_copy

extern __typeof (gdk_pixbuf_copy_area) IA__gdk_pixbuf_copy_area __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_copy_area) gdk_pixbuf_copy_area __attribute((alias("IA__gdk_pixbuf_copy_area"), visibility("default")));
#define gdk_pixbuf_copy_area IA__gdk_pixbuf_copy_area

extern __typeof (gdk_pixbuf_error_get_type) IA__gdk_pixbuf_error_get_type __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_error_get_type) gdk_pixbuf_error_get_type __attribute((alias("IA__gdk_pixbuf_error_get_type"), visibility("default")));
#define gdk_pixbuf_error_get_type IA__gdk_pixbuf_error_get_type

extern __typeof (gdk_pixbuf_error_quark) IA__gdk_pixbuf_error_quark __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_error_quark) gdk_pixbuf_error_quark __attribute((alias("IA__gdk_pixbuf_error_quark"), visibility("default")));
#define gdk_pixbuf_error_quark IA__gdk_pixbuf_error_quark

extern __typeof (gdk_pixbuf_fill) IA__gdk_pixbuf_fill __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_fill) gdk_pixbuf_fill __attribute((alias("IA__gdk_pixbuf_fill"), visibility("default")));
#define gdk_pixbuf_fill IA__gdk_pixbuf_fill

extern __typeof (gdk_pixbuf_flip) IA__gdk_pixbuf_flip __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_flip) gdk_pixbuf_flip __attribute((alias("IA__gdk_pixbuf_flip"), visibility("default")));
#define gdk_pixbuf_flip IA__gdk_pixbuf_flip

extern __typeof (gdk_pixbuf_format_get_description) IA__gdk_pixbuf_format_get_description __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_format_get_description) gdk_pixbuf_format_get_description __attribute((alias("IA__gdk_pixbuf_format_get_description"), visibility("default")));
#define gdk_pixbuf_format_get_description IA__gdk_pixbuf_format_get_description

extern __typeof (gdk_pixbuf_format_get_extensions) IA__gdk_pixbuf_format_get_extensions __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_format_get_extensions) gdk_pixbuf_format_get_extensions __attribute((alias("IA__gdk_pixbuf_format_get_extensions"), visibility("default")));
#define gdk_pixbuf_format_get_extensions IA__gdk_pixbuf_format_get_extensions

extern __typeof (gdk_pixbuf_format_get_license) IA__gdk_pixbuf_format_get_license __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_format_get_license) gdk_pixbuf_format_get_license __attribute((alias("IA__gdk_pixbuf_format_get_license"), visibility("default")));
#define gdk_pixbuf_format_get_license IA__gdk_pixbuf_format_get_license

extern __typeof (gdk_pixbuf_format_get_mime_types) IA__gdk_pixbuf_format_get_mime_types __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_format_get_mime_types) gdk_pixbuf_format_get_mime_types __attribute((alias("IA__gdk_pixbuf_format_get_mime_types"), visibility("default")));
#define gdk_pixbuf_format_get_mime_types IA__gdk_pixbuf_format_get_mime_types

extern __typeof (gdk_pixbuf_format_get_name) IA__gdk_pixbuf_format_get_name __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_format_get_name) gdk_pixbuf_format_get_name __attribute((alias("IA__gdk_pixbuf_format_get_name"), visibility("default")));
#define gdk_pixbuf_format_get_name IA__gdk_pixbuf_format_get_name

extern __typeof (gdk_pixbuf_format_is_disabled) IA__gdk_pixbuf_format_is_disabled __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_format_is_disabled) gdk_pixbuf_format_is_disabled __attribute((alias("IA__gdk_pixbuf_format_is_disabled"), visibility("default")));
#define gdk_pixbuf_format_is_disabled IA__gdk_pixbuf_format_is_disabled

extern __typeof (gdk_pixbuf_format_is_scalable) IA__gdk_pixbuf_format_is_scalable __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_format_is_scalable) gdk_pixbuf_format_is_scalable __attribute((alias("IA__gdk_pixbuf_format_is_scalable"), visibility("default")));
#define gdk_pixbuf_format_is_scalable IA__gdk_pixbuf_format_is_scalable

extern __typeof (gdk_pixbuf_format_is_writable) IA__gdk_pixbuf_format_is_writable __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_format_is_writable) gdk_pixbuf_format_is_writable __attribute((alias("IA__gdk_pixbuf_format_is_writable"), visibility("default")));
#define gdk_pixbuf_format_is_writable IA__gdk_pixbuf_format_is_writable

extern __typeof (gdk_pixbuf_format_set_disabled) IA__gdk_pixbuf_format_set_disabled __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_format_set_disabled) gdk_pixbuf_format_set_disabled __attribute((alias("IA__gdk_pixbuf_format_set_disabled"), visibility("default")));
#define gdk_pixbuf_format_set_disabled IA__gdk_pixbuf_format_set_disabled

extern __typeof (gdk_pixbuf_from_pixdata) IA__gdk_pixbuf_from_pixdata __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_from_pixdata) gdk_pixbuf_from_pixdata __attribute((alias("IA__gdk_pixbuf_from_pixdata"), visibility("default")));
#define gdk_pixbuf_from_pixdata IA__gdk_pixbuf_from_pixdata

extern __typeof (gdk_pixbuf_get_bits_per_sample) IA__gdk_pixbuf_get_bits_per_sample __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_get_bits_per_sample) gdk_pixbuf_get_bits_per_sample __attribute((alias("IA__gdk_pixbuf_get_bits_per_sample"), visibility("default")));
#define gdk_pixbuf_get_bits_per_sample IA__gdk_pixbuf_get_bits_per_sample

extern __typeof (gdk_pixbuf_get_colorspace) IA__gdk_pixbuf_get_colorspace __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_get_colorspace) gdk_pixbuf_get_colorspace __attribute((alias("IA__gdk_pixbuf_get_colorspace"), visibility("default")));
#define gdk_pixbuf_get_colorspace IA__gdk_pixbuf_get_colorspace

extern __typeof (gdk_pixbuf_get_file_info) IA__gdk_pixbuf_get_file_info __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_get_file_info) gdk_pixbuf_get_file_info __attribute((alias("IA__gdk_pixbuf_get_file_info"), visibility("default")));
#define gdk_pixbuf_get_file_info IA__gdk_pixbuf_get_file_info

extern __typeof (gdk_pixbuf_get_formats) IA__gdk_pixbuf_get_formats __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_get_formats) gdk_pixbuf_get_formats __attribute((alias("IA__gdk_pixbuf_get_formats"), visibility("default")));
#define gdk_pixbuf_get_formats IA__gdk_pixbuf_get_formats

extern __typeof (gdk_pixbuf_get_has_alpha) IA__gdk_pixbuf_get_has_alpha __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_get_has_alpha) gdk_pixbuf_get_has_alpha __attribute((alias("IA__gdk_pixbuf_get_has_alpha"), visibility("default")));
#define gdk_pixbuf_get_has_alpha IA__gdk_pixbuf_get_has_alpha

extern __typeof (gdk_pixbuf_get_height) IA__gdk_pixbuf_get_height __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_get_height) gdk_pixbuf_get_height __attribute((alias("IA__gdk_pixbuf_get_height"), visibility("default")));
#define gdk_pixbuf_get_height IA__gdk_pixbuf_get_height

extern __typeof (gdk_pixbuf_get_n_channels) IA__gdk_pixbuf_get_n_channels __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_get_n_channels) gdk_pixbuf_get_n_channels __attribute((alias("IA__gdk_pixbuf_get_n_channels"), visibility("default")));
#define gdk_pixbuf_get_n_channels IA__gdk_pixbuf_get_n_channels

extern __typeof (gdk_pixbuf_get_option) IA__gdk_pixbuf_get_option __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_get_option) gdk_pixbuf_get_option __attribute((alias("IA__gdk_pixbuf_get_option"), visibility("default")));
#define gdk_pixbuf_get_option IA__gdk_pixbuf_get_option

extern __typeof (gdk_pixbuf_get_pixels) IA__gdk_pixbuf_get_pixels __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_get_pixels) gdk_pixbuf_get_pixels __attribute((alias("IA__gdk_pixbuf_get_pixels"), visibility("default")));
#define gdk_pixbuf_get_pixels IA__gdk_pixbuf_get_pixels

extern __typeof (gdk_pixbuf_get_rowstride) IA__gdk_pixbuf_get_rowstride __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_get_rowstride) gdk_pixbuf_get_rowstride __attribute((alias("IA__gdk_pixbuf_get_rowstride"), visibility("default")));
#define gdk_pixbuf_get_rowstride IA__gdk_pixbuf_get_rowstride

extern __typeof (gdk_pixbuf_get_type) IA__gdk_pixbuf_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
extern __typeof (gdk_pixbuf_get_type) gdk_pixbuf_get_type __attribute((alias("IA__gdk_pixbuf_get_type"), visibility("default")));
#define gdk_pixbuf_get_type IA__gdk_pixbuf_get_type

extern __typeof (gdk_pixbuf_get_width) IA__gdk_pixbuf_get_width __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_get_width) gdk_pixbuf_get_width __attribute((alias("IA__gdk_pixbuf_get_width"), visibility("default")));
#define gdk_pixbuf_get_width IA__gdk_pixbuf_get_width

extern __typeof (gdk_pixbuf_loader_close) IA__gdk_pixbuf_loader_close __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_loader_close) gdk_pixbuf_loader_close __attribute((alias("IA__gdk_pixbuf_loader_close"), visibility("default")));
#define gdk_pixbuf_loader_close IA__gdk_pixbuf_loader_close

extern __typeof (gdk_pixbuf_loader_get_animation) IA__gdk_pixbuf_loader_get_animation __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_loader_get_animation) gdk_pixbuf_loader_get_animation __attribute((alias("IA__gdk_pixbuf_loader_get_animation"), visibility("default")));
#define gdk_pixbuf_loader_get_animation IA__gdk_pixbuf_loader_get_animation

extern __typeof (gdk_pixbuf_loader_get_format) IA__gdk_pixbuf_loader_get_format __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_loader_get_format) gdk_pixbuf_loader_get_format __attribute((alias("IA__gdk_pixbuf_loader_get_format"), visibility("default")));
#define gdk_pixbuf_loader_get_format IA__gdk_pixbuf_loader_get_format

extern __typeof (gdk_pixbuf_loader_get_pixbuf) IA__gdk_pixbuf_loader_get_pixbuf __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_loader_get_pixbuf) gdk_pixbuf_loader_get_pixbuf __attribute((alias("IA__gdk_pixbuf_loader_get_pixbuf"), visibility("default")));
#define gdk_pixbuf_loader_get_pixbuf IA__gdk_pixbuf_loader_get_pixbuf

extern __typeof (gdk_pixbuf_loader_get_type) IA__gdk_pixbuf_loader_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
extern __typeof (gdk_pixbuf_loader_get_type) gdk_pixbuf_loader_get_type __attribute((alias("IA__gdk_pixbuf_loader_get_type"), visibility("default")));
#define gdk_pixbuf_loader_get_type IA__gdk_pixbuf_loader_get_type

extern __typeof (gdk_pixbuf_loader_new) IA__gdk_pixbuf_loader_new __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_loader_new) gdk_pixbuf_loader_new __attribute((alias("IA__gdk_pixbuf_loader_new"), visibility("default")));
#define gdk_pixbuf_loader_new IA__gdk_pixbuf_loader_new

extern __typeof (gdk_pixbuf_loader_new_with_mime_type) IA__gdk_pixbuf_loader_new_with_mime_type __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_loader_new_with_mime_type) gdk_pixbuf_loader_new_with_mime_type __attribute((alias("IA__gdk_pixbuf_loader_new_with_mime_type"), visibility("default")));
#define gdk_pixbuf_loader_new_with_mime_type IA__gdk_pixbuf_loader_new_with_mime_type

extern __typeof (gdk_pixbuf_loader_new_with_type) IA__gdk_pixbuf_loader_new_with_type __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_loader_new_with_type) gdk_pixbuf_loader_new_with_type __attribute((alias("IA__gdk_pixbuf_loader_new_with_type"), visibility("default")));
#define gdk_pixbuf_loader_new_with_type IA__gdk_pixbuf_loader_new_with_type

extern __typeof (gdk_pixbuf_loader_set_size) IA__gdk_pixbuf_loader_set_size __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_loader_set_size) gdk_pixbuf_loader_set_size __attribute((alias("IA__gdk_pixbuf_loader_set_size"), visibility("default")));
#define gdk_pixbuf_loader_set_size IA__gdk_pixbuf_loader_set_size

extern __typeof (gdk_pixbuf_loader_write) IA__gdk_pixbuf_loader_write __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_loader_write) gdk_pixbuf_loader_write __attribute((alias("IA__gdk_pixbuf_loader_write"), visibility("default")));
#define gdk_pixbuf_loader_write IA__gdk_pixbuf_loader_write

extern __typeof (gdk_pixbuf_new) IA__gdk_pixbuf_new __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_new) gdk_pixbuf_new __attribute((alias("IA__gdk_pixbuf_new"), visibility("default")));
#define gdk_pixbuf_new IA__gdk_pixbuf_new

extern __typeof (gdk_pixbuf_new_from_data) IA__gdk_pixbuf_new_from_data __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_new_from_data) gdk_pixbuf_new_from_data __attribute((alias("IA__gdk_pixbuf_new_from_data"), visibility("default")));
#define gdk_pixbuf_new_from_data IA__gdk_pixbuf_new_from_data

extern __typeof (gdk_pixbuf_new_from_file) IA__gdk_pixbuf_new_from_file __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_new_from_file) gdk_pixbuf_new_from_file __attribute((alias("IA__gdk_pixbuf_new_from_file"), visibility("default")));
#define gdk_pixbuf_new_from_file IA__gdk_pixbuf_new_from_file

#ifdef G_OS_WIN32
extern __typeof (gdk_pixbuf_new_from_file_utf8) IA__gdk_pixbuf_new_from_file_utf8 __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_new_from_file_utf8) gdk_pixbuf_new_from_file_utf8 __attribute((alias("IA__gdk_pixbuf_new_from_file_utf8"), visibility("default")));
#define gdk_pixbuf_new_from_file_utf8 IA__gdk_pixbuf_new_from_file_utf8

#endif
extern __typeof (gdk_pixbuf_new_from_file_at_size) IA__gdk_pixbuf_new_from_file_at_size __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_new_from_file_at_size) gdk_pixbuf_new_from_file_at_size __attribute((alias("IA__gdk_pixbuf_new_from_file_at_size"), visibility("default")));
#define gdk_pixbuf_new_from_file_at_size IA__gdk_pixbuf_new_from_file_at_size

#ifdef G_OS_WIN32
extern __typeof (gdk_pixbuf_new_from_file_at_size_utf8) IA__gdk_pixbuf_new_from_file_at_size_utf8 __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_new_from_file_at_size_utf8) gdk_pixbuf_new_from_file_at_size_utf8 __attribute((alias("IA__gdk_pixbuf_new_from_file_at_size_utf8"), visibility("default")));
#define gdk_pixbuf_new_from_file_at_size_utf8 IA__gdk_pixbuf_new_from_file_at_size_utf8

#endif
extern __typeof (gdk_pixbuf_new_from_file_at_scale) IA__gdk_pixbuf_new_from_file_at_scale __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_new_from_file_at_scale) gdk_pixbuf_new_from_file_at_scale __attribute((alias("IA__gdk_pixbuf_new_from_file_at_scale"), visibility("default")));
#define gdk_pixbuf_new_from_file_at_scale IA__gdk_pixbuf_new_from_file_at_scale

#ifdef G_OS_WIN32
extern __typeof (gdk_pixbuf_new_from_file_at_scale_utf8) IA__gdk_pixbuf_new_from_file_at_scale_utf8 __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_new_from_file_at_scale_utf8) gdk_pixbuf_new_from_file_at_scale_utf8 __attribute((alias("IA__gdk_pixbuf_new_from_file_at_scale_utf8"), visibility("default")));
#define gdk_pixbuf_new_from_file_at_scale_utf8 IA__gdk_pixbuf_new_from_file_at_scale_utf8

#endif
extern __typeof (gdk_pixbuf_new_from_inline) IA__gdk_pixbuf_new_from_inline __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_new_from_inline) gdk_pixbuf_new_from_inline __attribute((alias("IA__gdk_pixbuf_new_from_inline"), visibility("default")));
#define gdk_pixbuf_new_from_inline IA__gdk_pixbuf_new_from_inline

extern __typeof (gdk_pixbuf_new_from_xpm_data) IA__gdk_pixbuf_new_from_xpm_data __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_new_from_xpm_data) gdk_pixbuf_new_from_xpm_data __attribute((alias("IA__gdk_pixbuf_new_from_xpm_data"), visibility("default")));
#define gdk_pixbuf_new_from_xpm_data IA__gdk_pixbuf_new_from_xpm_data

extern __typeof (gdk_pixbuf_new_subpixbuf) IA__gdk_pixbuf_new_subpixbuf __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_new_subpixbuf) gdk_pixbuf_new_subpixbuf __attribute((alias("IA__gdk_pixbuf_new_subpixbuf"), visibility("default")));
#define gdk_pixbuf_new_subpixbuf IA__gdk_pixbuf_new_subpixbuf

extern __typeof (gdk_pixbuf_non_anim_new) IA__gdk_pixbuf_non_anim_new __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_non_anim_new) gdk_pixbuf_non_anim_new __attribute((alias("IA__gdk_pixbuf_non_anim_new"), visibility("default")));
#define gdk_pixbuf_non_anim_new IA__gdk_pixbuf_non_anim_new

extern __typeof (gdk_pixbuf_ref) IA__gdk_pixbuf_ref __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_ref) gdk_pixbuf_ref __attribute((alias("IA__gdk_pixbuf_ref"), visibility("default")));
#define gdk_pixbuf_ref IA__gdk_pixbuf_ref

extern __typeof (gdk_pixbuf_rotate_simple) IA__gdk_pixbuf_rotate_simple __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_rotate_simple) gdk_pixbuf_rotate_simple __attribute((alias("IA__gdk_pixbuf_rotate_simple"), visibility("default")));
#define gdk_pixbuf_rotate_simple IA__gdk_pixbuf_rotate_simple

extern __typeof (gdk_pixbuf_rotation_get_type) IA__gdk_pixbuf_rotation_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
extern __typeof (gdk_pixbuf_rotation_get_type) gdk_pixbuf_rotation_get_type __attribute((alias("IA__gdk_pixbuf_rotation_get_type"), visibility("default")));
#define gdk_pixbuf_rotation_get_type IA__gdk_pixbuf_rotation_get_type

extern __typeof (gdk_pixbuf_saturate_and_pixelate) IA__gdk_pixbuf_saturate_and_pixelate __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_saturate_and_pixelate) gdk_pixbuf_saturate_and_pixelate __attribute((alias("IA__gdk_pixbuf_saturate_and_pixelate"), visibility("default")));
#define gdk_pixbuf_saturate_and_pixelate IA__gdk_pixbuf_saturate_and_pixelate

extern __typeof (gdk_pixbuf_save) IA__gdk_pixbuf_save __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_save) gdk_pixbuf_save __attribute((alias("IA__gdk_pixbuf_save"), visibility("default")));
#define gdk_pixbuf_save IA__gdk_pixbuf_save

extern __typeof (gdk_pixbuf_save_to_buffer) IA__gdk_pixbuf_save_to_buffer __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_save_to_buffer) gdk_pixbuf_save_to_buffer __attribute((alias("IA__gdk_pixbuf_save_to_buffer"), visibility("default")));
#define gdk_pixbuf_save_to_buffer IA__gdk_pixbuf_save_to_buffer

extern __typeof (gdk_pixbuf_save_to_bufferv) IA__gdk_pixbuf_save_to_bufferv __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_save_to_bufferv) gdk_pixbuf_save_to_bufferv __attribute((alias("IA__gdk_pixbuf_save_to_bufferv"), visibility("default")));
#define gdk_pixbuf_save_to_bufferv IA__gdk_pixbuf_save_to_bufferv

extern __typeof (gdk_pixbuf_save_to_callback) IA__gdk_pixbuf_save_to_callback __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_save_to_callback) gdk_pixbuf_save_to_callback __attribute((alias("IA__gdk_pixbuf_save_to_callback"), visibility("default")));
#define gdk_pixbuf_save_to_callback IA__gdk_pixbuf_save_to_callback

extern __typeof (gdk_pixbuf_save_to_callbackv) IA__gdk_pixbuf_save_to_callbackv __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_save_to_callbackv) gdk_pixbuf_save_to_callbackv __attribute((alias("IA__gdk_pixbuf_save_to_callbackv"), visibility("default")));
#define gdk_pixbuf_save_to_callbackv IA__gdk_pixbuf_save_to_callbackv

extern __typeof (gdk_pixbuf_savev) IA__gdk_pixbuf_savev __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_savev) gdk_pixbuf_savev __attribute((alias("IA__gdk_pixbuf_savev"), visibility("default")));
#define gdk_pixbuf_savev IA__gdk_pixbuf_savev

extern __typeof (gdk_pixbuf_scale) IA__gdk_pixbuf_scale __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_scale) gdk_pixbuf_scale __attribute((alias("IA__gdk_pixbuf_scale"), visibility("default")));
#define gdk_pixbuf_scale IA__gdk_pixbuf_scale

extern __typeof (gdk_pixbuf_scale_simple) IA__gdk_pixbuf_scale_simple __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_scale_simple) gdk_pixbuf_scale_simple __attribute((alias("IA__gdk_pixbuf_scale_simple"), visibility("default")));
#define gdk_pixbuf_scale_simple IA__gdk_pixbuf_scale_simple

extern __typeof (gdk_pixbuf_set_option) IA__gdk_pixbuf_set_option __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_set_option) gdk_pixbuf_set_option __attribute((alias("IA__gdk_pixbuf_set_option"), visibility("default")));
#define gdk_pixbuf_set_option IA__gdk_pixbuf_set_option

extern __typeof (gdk_pixbuf_unref) IA__gdk_pixbuf_unref __attribute((visibility("hidden")));
extern __typeof (gdk_pixbuf_unref) gdk_pixbuf_unref __attribute((alias("IA__gdk_pixbuf_unref"), visibility("default")));
#define gdk_pixbuf_unref IA__gdk_pixbuf_unref

extern __typeof (gdk_pixdata_deserialize) IA__gdk_pixdata_deserialize __attribute((visibility("hidden")));
extern __typeof (gdk_pixdata_deserialize) gdk_pixdata_deserialize __attribute((alias("IA__gdk_pixdata_deserialize"), visibility("default")));
#define gdk_pixdata_deserialize IA__gdk_pixdata_deserialize

extern __typeof (gdk_pixdata_from_pixbuf) IA__gdk_pixdata_from_pixbuf __attribute((visibility("hidden")));
extern __typeof (gdk_pixdata_from_pixbuf) gdk_pixdata_from_pixbuf __attribute((alias("IA__gdk_pixdata_from_pixbuf"), visibility("default")));
#define gdk_pixdata_from_pixbuf IA__gdk_pixdata_from_pixbuf

extern __typeof (gdk_pixdata_serialize) IA__gdk_pixdata_serialize __attribute((visibility("hidden")));
extern __typeof (gdk_pixdata_serialize) gdk_pixdata_serialize __attribute((alias("IA__gdk_pixdata_serialize"), visibility("default")));
#define gdk_pixdata_serialize IA__gdk_pixdata_serialize

extern __typeof (gdk_pixdata_to_csource) IA__gdk_pixdata_to_csource __attribute((visibility("hidden")));
extern __typeof (gdk_pixdata_to_csource) gdk_pixdata_to_csource __attribute((alias("IA__gdk_pixdata_to_csource"), visibility("default")));
#define gdk_pixdata_to_csource IA__gdk_pixdata_to_csource


#ifdef  WAS_NO_DEPR
#define GDK_PIXBUF_DISABLE_DEPRECATED
#undef  WAS_NO_DEPR
#endif

#ifdef  WAS_NO_G_DEPR
#define G_DISABLE_DEPRECATED
#undef  WAS_NO_G_DEPR
#endif

#endif /* G_HAVE_GNUC_VISIBILITY */

#endif /* DISABLE_VISIBILITY */
