# Generated by setup.py do not modify
import os
prefix = r"/usr"
pixmaps_dir = os.path.join(prefix, 'share', 'gazpacho', 'pixmaps')
languages_dir = os.path.join(prefix, 'share', 'locale')
catalogs_dir = os.path.join(prefix, 'share', 'gazpacho', 'catalogs')
resources_dir = os.path.join(prefix, 'share', 'gazpacho', 'resources')
glade_dir = os.path.join(prefix, 'share', 'gazpacho', 'glade')
docs_dir = os.path.join(prefix, 'share', 'doc', 'gazpacho')
