#!/bin/sh
TGT=''
if [ -e /targets/links/scratchbox.config ] ; then
  . /targets/links/scratchbox.config
  TGT=$SBOX_TARGET_DIR
  USER=user
fi

HOME="$TGT/home/$USER"
if [ ! -d $HOME/.osso ]; then
  mkdir -p $HOME/.osso
  chown user:users $HOME/.osso
fi

DEFAULTCONF=$HOME/.osso/current-gtk-theme
if [ ! -e $DEFAULTCONF ]; then
  cp -f /etc/osso-af-init/current-gtk-theme.default $DEFAULTCONF
  chown user:users $DEFAULTCONF
fi
