.\"     Title: apt\-key
.\"    Author: Jason Gunthorpe
.\" Generator: DocBook XSL Stylesheets v1.71.0 <http://docbook.sf.net/>
.\"      Date: 14 December 2003
.\"    Manual: 
.\"    Source: Linux
.\"
.TH "APT\-KEY" "8" "14 December 2003" "Linux" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
apt\-key \- APT キー管理ユーティリティ
.SH "SYNOPSIS"
.HP 8
\fBapt\-key\fR [\fIcommand\fR/] [\fB\fIarguments\fR\fR...]
.SH "説明"
.PP


\fBapt\-key\fR
は、 apt が パッケージを認証するのに使用するキーの一覧を管理するのに使用します。 このキーで認証されたパッケージは、信頼するに足ると見なせるでしょう。
.SH "コマンド"
.PP
add \fIfilename\fR
.RS 3n

信頼キー一覧に新しいキーを追加します。 このキーは
\fIfilename\fR
から読み込みますが、
\fIfilename\fR
を
\-
とすると、 標準入力から読み込みます。
.RE
.PP
del \fIkeyid\fR
.RS 3n

信頼キー一覧からキーを削除します。
.RE
.PP
list
.RS 3n

信頼キーを一覧表示します。
.RE
.PP
update
.RS 3n

Debian アーカイブキーで、ローカルキーリングを更新し、 もう有効でないキーをキーリングから削除します。
.RE
.SH "ファイル"
.PP
\fI/etc/apt/trusted.gpg\fR
.RS 3n
ローカル信頼キーのキーリング。 新しいキーはここに追加されます。
.RE
.PP
\fI/etc/apt/trustdb.gpg\fR
.RS 3n
アーカイブキーのローカル信頼データベース
.RE
.PP
\fI/usr/share/keyrings/debian\-archive\-keyring.gpg\fR
.RS 3n
Debian アーカイブ信頼キーのキーリング
.RE
.PP
\fI/usr/share/keyrings/debian\-archive\-removed\-keys.gpg\fR
.RS 3n
削除された Debian アーカイブ信頼キーのキーリング
.RE
.SH "関連項目"
.PP

\fBapt\-get\fR(8),
\fBapt\-secure\fR(8)
.SH "バグ"
.PP
[1]\&\fIAPT バグページ\fRを ご覧ください。 APT のバグを報告する場合は、
\fI/usr/share/doc/debian/bug\-reporting.txt\fR
や
\fBreportbug\fR(1)
コマンドをご覧ください。
.SH "著者"
.PP
APT は the APT team
<apt@packages.debian.org>
によって 書かれました。
.SH "訳者"
.PP
倉澤 望
<nabetaro@debian.or.jp>
(2003\-2006), Debian JP Documentation ML
<debian\-doc@debian.or.jp>
.SH "AUTHOR"
.PP
\fBJason Gunthorpe\fR
.sp -1n
.IP "" 3n
Author.
.SH "COPYRIGHT"
Copyright \(co 1998\-2001 Jason Gunthorpe
.br
.SH "REFERENCES"
.TP 3
1.\ APT バグページ
\%http://bugs.debian.org/src:apt
