.\"     Title: apt\-extracttemplates
.\"    Author: Jason Gunthorpe
.\" Generator: DocBook XSL Stylesheets v1.71.0 <http://docbook.sf.net/>
.\"      Date: 29 February 2004
.\"    Manual: 
.\"    Source: Linux
.\"
.TH "APT\-EXTRACTTEMPLATES" "1" "29 February 2004" "Linux" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
apt\-extracttemplates \- Debian パッケージから DebConf 設定とテンプレートを抽出するユーティリティ
.SH "SYNOPSIS"
.HP 21
\fBapt\-extracttemplates\fR [\fB\-hv\fR] [\fB\-t=\fR\fB\fItemporary\ directory\fR\fR] \fIfile\fR...
.SH "説明"
.PP
\fBapt\-extracttemplates\fR
は、 入力に複数の Debian パッケージをとり、 関連する設定スクリプトとテンプレートファイルを (一時ディレクトリに) 出力します。 設定スクリプト・テンプレートファイルを持つ、 渡されたパッケージそれぞれに対し、以下の形式で 1 行ずつ出力します。
.PP
package version template\-file config\-script
.PP
テンプレートファイルや、設定スクリプトは、 \-t や \-\-tempdir で指定した一時ディレクトリ (APT::ExtractTemplates::TempDir) に書き出され、 ファイル名は、\fIpackage.template.XXXX\fR
や
\fIpackage.config.XXXX\fR
と言った形になります。
.SH "オプション"
.PP
この説明で示したオプションは、 すべて設定ファイルを使用して設定できます。 設定ファイルに書いた真偽値をとるオプションは
\fB\-f\-\fR,\fB\-\-no\-f\fR,
\fB\-f=no\fR
などのようにして上書きできます。
.PP
\fB\-t\fR, \fB\-\-tempdir\fR
.RS 3n
抽出した debconf テンプレートファイルや設定スクリプトを書き出す、 一時ディレクトリ。 設定項目 \-
APT::ExtractTemplates::TempDir
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 3n
使い方の短い要約を表示します。
.RE
.PP
\fB\-v\fR, \fB\-\-version\fR
.RS 3n
プログラムのバージョンを表示します。
.RE
.PP
\fB\-c\fR, \fB\-\-config\-file\fR
.RS 3n
設定ファイル。 使用する設定ファイルを指定します。 この設定ファイルが読めない場合はデフォルトの設定ファイルを読み込みます。 文法については
\fBapt.conf\fR(5)
を参照してください。
.RE
.PP
\fB\-o\fR, \fB\-\-option\fR
.RS 3n
設定オプションのセット。任意の設定オプションをセットします。 文法は
\fB\-o Foo::Bar=bar\fR
となります。
.RE
.SH "関連項目"
.PP
\fBapt.conf\fR(5)
.SH "診断メッセージ"
.PP
\fBapt\-extracttemplates\fR
は正常終了時に 0 を返します。 エラー時には十進の 100 を返します。
.SH "バグ"
.PP
[1]\&\fIAPT バグページ\fRを ご覧ください。 APT のバグを報告する場合は、
\fI/usr/share/doc/debian/bug\-reporting.txt\fR
や
\fBreportbug\fR(1)
コマンドをご覧ください。
.SH "訳者"
.PP
倉澤 望
<nabetaro@debian.or.jp>
(2003\-2006), Debian JP Documentation ML
<debian\-doc@debian.or.jp>
.SH "AUTHORS"
.PP
\fBJason Gunthorpe\fR
.sp -1n
.IP "" 3n
Author.
.PP
\fBAPT team\fR
.sp -1n
.IP "" 3n
Author.
.SH "REFERENCES"
.TP 3
1.\ APT バグページ
\%http://bugs.debian.org/src:apt
