.\"     Title: apt\-sortpkgs
.\"    Author: Jason Gunthorpe
.\" Generator: DocBook XSL Stylesheets v1.71.0 <http://docbook.sf.net/>
.\"      Date: 29 February 2004
.\"    Manual: 
.\"    Source: Linux
.\"
.TH "APT\-SORTPKGS" "1" "29 February 2004" "Linux" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
apt\-sortpkgs \- パッケージインデックスファイルのソートユーティリティ
.SH "SYNOPSIS"
.HP 13
\fBapt\-sortpkgs\fR [\fB\-hvs\fR] [\fB\-o=\fR\fB\fIconfig\ string\fR\fR] [\fB\-c=\fR\fB\fIfile\fR\fR] \fIfile\fR...
.SH "説明"
.PP
\fBapt\-sortpkgs\fR
は、インデックスファイル (ソースインデックスやパッケージインデックス) からレコードをソートし、 パッケージ名順に整えます。 また、内部のソート規則に従って、内部フィールドについてもソートを行います。
.PP
出力はすべて標準出力に送られ、入力は検索できるファイルでなければなりません。
.SH "オプション"
.PP
この説明で示したオプションは、 すべて設定ファイルを使用して設定できます。 設定ファイルに書いた真偽値をとるオプションは
\fB\-f\-\fR,\fB\-\-no\-f\fR,
\fB\-f=no\fR
などのようにして上書きできます。
.PP
\fB\-s\fR, \fB\-\-source\fR
.RS 3n

ソースインデックスフィールド順に並べ替え 設定項目 \-
APT::SortPkgs::Source.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 3n
使い方の短い要約を表示します。
.RE
.PP
\fB\-v\fR, \fB\-\-version\fR
.RS 3n
プログラムのバージョンを表示します。
.RE
.PP
\fB\-c\fR, \fB\-\-config\-file\fR
.RS 3n
設定ファイル。 使用する設定ファイルを指定します。 この設定ファイルが読めない場合はデフォルトの設定ファイルを読み込みます。 文法については
\fBapt.conf\fR(5)
を参照してください。
.RE
.PP
\fB\-o\fR, \fB\-\-option\fR
.RS 3n
設定オプションのセット。任意の設定オプションをセットします。 文法は
\fB\-o Foo::Bar=bar\fR
となります。
.RE
.SH "関連項目"
.PP
\fBapt.conf\fR(5)
.SH "診断メッセージ"
.PP
\fBapt\-sortpkgs\fR
は正常終了時に 0 を返します。 エラー時には十進の 100 を返します。
.SH "バグ"
.PP
[1]\&\fIAPT バグページ\fRを ご覧ください。 APT のバグを報告する場合は、
\fI/usr/share/doc/debian/bug\-reporting.txt\fR
や
\fBreportbug\fR(1)
コマンドをご覧ください。
.SH "訳者"
.PP
倉澤 望
<nabetaro@debian.or.jp>
(2003\-2006), Debian JP Documentation ML
<debian\-doc@debian.or.jp>
.SH "AUTHORS"
.PP
\fBJason Gunthorpe\fR
.sp -1n
.IP "" 3n
Author.
.PP
\fBAPT team\fR
.sp -1n
.IP "" 3n
Author.
.SH "REFERENCES"
.TP 3
1.\ APT バグページ
\%http://bugs.debian.org/src:apt
