.\"     Title: apt\-cdrom
.\"    Author: Jason Gunthorpe
.\" Generator: DocBook XSL Stylesheets v1.71.0 <http://docbook.sf.net/>
.\"      Date: 14 February 2004
.\"    Manual: 
.\"    Source: Linux
.\"
.TH "APT\-CDROM" "8" "14 February 2004" "Linux" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
apt\-cdrom \- APT CDROM 管理ユーティリティ
.SH "SYNOPSIS"
.HP 10
\fBapt\-cdrom\fR [\fB\-hvrmfan\fR] [\fB\-d=\fR\fB\fIcdrom\ mount\ point\fR\fR] [\fB\-o=\fR\fB\fIconfig\ string\fR\fR] [\fB\-c=\fR\fB\fIfile\fR\fR] [[add] | [ident]]
.SH "説明"
.PP
\fBapt\-cdrom\fR
は利用可能な取得元として、 APT のリストに新しい CDROM を追加するのに便利です。
\fBapt\-cdrom\fR
は焼き損じを可能な限り補正し、 ディスク構造の確認を助けます。また、インデックスファイルの確認を行います。
.PP
APT システムに手作業で CD を追加するのは難しいため、
\fBapt\-cdrom\fR
が必要になります。 その上、CD セットのディスクを 1 枚づつ、 焼き損じを補正できるか評価しなければなりません。
.PP
\fB\-h\fR
オプションや
\fB\-\-help\fR
オプションを除き、 以下に挙げるコマンドが必要です。
.PP
add
.RS 3n
add
は、 新しいディスクを取得元リストに追加します。 CDROM デバイスのアンマウント、ディスク挿入のプロンプトの表示の後に、 ディスクのスキャンとインデックスファイルのコピーを行います。 ディスクに正しい
\fIdisk\fR
ディレクトリが存在しない場合、 タイトルを入力するよう促します。
.sp
APT は、現在ドライブにあるディスクのトラックから取得した、 CDROM ID を使用します。またその ID を、
\fI/var/lib/apt/cdroms.list\fR
内のデータベースで管理します。
.RE
.PP
ident
.RS 3n
格納されているファイル名と、 現在のディスクが同一かどうかをレポートする、デバッグツールです。
.RE
.SH "OPTIONS"
.PP
この説明で示したオプションは、 すべて設定ファイルを使用して設定できます。 設定ファイルに書いた真偽値をとるオプションは
\fB\-f\-\fR,\fB\-\-no\-f\fR,
\fB\-f=no\fR
などのようにして上書きできます。
.PP
\fB\-d\fR, \fB\-\-cdrom\fR
.RS 3n
マウントポイント \- cdrom をマウントする場所を指定します。 このマウントポイントは、
\fI/etc/fstab\fR
に正しく設定されている必要があります。 設定項目 \-
Acquire::cdrom::mount
.RE
.PP
\fB\-r\fR, \fB\-\-rename\fR
.RS 3n
ディスクの名前変更 \- 指定した名前でディスクのラベルを変更・更新します。このオプションにより、
\fBapt\-cdrom\fR
が新しいラベルを入力するよう促します。 設定項目 \-
APT::CDROM::Rename
.RE
.PP
\fB\-m\fR, \fB\-\-no\-mount\fR
.RS 3n
マウントなし \-
\fBapt\-cdrom\fR
が、 マウントポイントにマウント・アンマウントしないようにします。 設定項目 \-
APT::CDROM::NoMount
.RE
.PP
\fB\-f\fR, \fB\-\-fast\fR
.RS 3n
高速コピー \- パッケージファイルが妥当であると仮定し、 チェックを全く行いません。このオプションは、 このディスクで以前
\fBapt\-cdrom\fR
を行っており、 エラーを検出しなかった場合のみ使用すべきです。 設定項目 \-
APT::CDROM::Fast
.RE
.PP
\fB\-a\fR, \fB\-\-thorough\fR
.RS 3n
完全パッケージスキャン \- 古い Debian 1.1/1.2 のディスクは、パッケージファイルが違う場所にあるため、 このオプションを使う必要があるかもしれません。 CD をスキャンするのに非常に時間がかかりますが、 全パッケージファイルを抽出することができます。
.RE
.PP
\fB\-n\fR, \fB\-\-just\-print\fR, \fB\-\-recon\fR, \fB\-\-no\-act\fR
.RS 3n
変更なし \-
\fBsources.list\fR(5)
ファイルの変更や、 インデックスファイルの書き込みを行いません。 とはいえ、すべてのチェックは行います。 設定項目 \-
APT::CDROM::NoAct
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 3n
使い方の短い要約を表示します。
.RE
.PP
\fB\-v\fR, \fB\-\-version\fR
.RS 3n
プログラムのバージョンを表示します。
.RE
.PP
\fB\-c\fR, \fB\-\-config\-file\fR
.RS 3n
設定ファイル。 使用する設定ファイルを指定します。 この設定ファイルが読めない場合はデフォルトの設定ファイルを読み込みます。 文法については
\fBapt.conf\fR(5)
を参照してください。
.RE
.PP
\fB\-o\fR, \fB\-\-option\fR
.RS 3n
設定オプションのセット。任意の設定オプションをセットします。 文法は
\fB\-o Foo::Bar=bar\fR
となります。
.RE
.SH "関連項目"
.PP
\fBapt.conf\fR(5),
\fBapt\-get\fR(8),
\fBsources.list\fR(5)
.SH "診断メッセージ"
.PP
\fBapt\-cdrom\fR
は正常終了時に 0 を返します。 エラー時には十進の 100 を返します。
.SH "バグ"
.PP
[1]\&\fIAPT バグページ\fRを ご覧ください。 APT のバグを報告する場合は、
\fI/usr/share/doc/debian/bug\-reporting.txt\fR
や
\fBreportbug\fR(1)
コマンドをご覧ください。
.SH "訳者"
.PP
倉澤 望
<nabetaro@debian.or.jp>
(2003\-2006), Debian JP Documentation ML
<debian\-doc@debian.or.jp>
.SH "AUTHORS"
.PP
\fBJason Gunthorpe\fR
.sp -1n
.IP "" 3n
Author.
.PP
\fBAPT team\fR
.sp -1n
.IP "" 3n
Author.
.SH "REFERENCES"
.TP 3
1.\ APT バグページ
\%http://bugs.debian.org/src:apt
