#!/bin/sh -e

# We try to support upgrade path from older dists
# First check if there is an existing old-default directory 
# and try moving it around a bit
if [[ -d '/usr/share/themes/default' && ! -h '/usr/share/themes/default' ]]; then
  echo "Moving 'default' theme to 'theme0'..."
  mv "/usr/share/themes/default" "/usr/share/themes/theme0"
fi

# Remove the existing symlink if it exists
if [ -h '/usr/share/themes/default' ]; then
  echo "Removing existing 'default' theme symlink"
  rm -f '/usr/share/themes/default'
fi

# Create a symlink to default theme
echo "Creating a theme symlink 'default' => 'plankton' in /usr/share/themes"
ln -s '/usr/share/themes/plankton' '/usr/share/themes/default'

# Remove the existing symlink to the default wallpaper if it exists
if [ -h '/usr/share/backgrounds/default.desktop' ]; then
  echo "Removing existing 'default.desktop' wallpaper symlink"
  rm -f '/usr/share/backgrounds/default.desktop'
fi

# Create a symlink to default wallpaper
echo "Creating a default wallpaper symlink 'default.desktop' => 'plankton.desktop' in /usr/share/backgrounds"
ln -s '/usr/share/backgrounds/plankton.desktop' '/usr/share/backgrounds/default.desktop'

exit 0
