# Copyright (C) 2004,2005 by SICEm S.L. and Imendio
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
GLADE_CATALOG                   = "glade-catalog"
GLADE_WIDGET_CLASSES            = "glade-widget-classes"
GLADE_WIDGET_CLASS              = "glade-widget-class"
GLADE_WIDGET_GROUP              = "glade-widget-group"
GLADE_WIDGET_CLASS_REF          = "glade-widget-class-ref"
LIBGLADE_MODULE                 = "libglade-module"
ADAPTOR_CLASS                   = "adaptor-class"
NAME                            = "name"
PRIORITY                        = "priority"
GENERIC_NAME                    = "generic-name"
FUNCTION                        = "function"
TITLE                           = "title"
LIBRARY                         = "library"
LIBRARY_TYPE                    = "library-type"
RESOURCE_PATH                   = "resource-path"
ID                              = "id"
KEY                             = "key"
VALUE                           = "value"
COMMON                          = "common"
OPTIONAL                        = "optional"
OPTIONAL_DEFAULT                = "optional-default"
PROPERTY                        = "property"
TRANSLATABLE                    = "translatable"
TYPE                            = "type"
TOOLTIP                         = "tooltip"
PARAMETERS                      = "parameters"
PARAMETER                       = "parameter"
OTHER_WIDGETS                   = "other-widgets"
VISIBILITY                      = "visibility"
GET                             = "get"
SET                             = "set"
SAVE                            = "save"
LOAD                            = "load"
VISIBLE_LINES                   = "visible-lines"
PROPERTIES                      = "properties"
CHILD_PROPERTIES                = "child-properties"
ENUM_DATA_TAG                   = "glade-enum-data-tag"
FLAGS_DATA_TAG                  = "glade-flags-data-tag"
DEFAULT                         = "default"
DISABLED                        = "disabled"
EDITABLE                        = "editable"
EDITOR                          = "editor"
CREATE                          = "create"
UPDATE                          = "update"
EVENT_HANDLER_CONNECTED         = "event-handler-connected"
SIGNAL_HANDLER                  = "signal-handler"
PACKING_DEFAULTS                = "packing-defaults"
PARENT_CLASS                    = "parent-class"
CHILD_PROPERTY                  = "child-property"
WIDE                            = "wide"
ENUM                            = "Enum"
ENUMS                           = "Enums"
ENUM_TYPE                       = "EnumType"
OBJECT                          = "Object"
STRING                          = "String"
BOOLEAN                         = "Boolean"
UNICHAR                         = "Unichar"
FLOAT                           = "Float"
INTEGER                         = "Integer"
UINTEGER                        = "Uinteger"
ENUM                            = "Enum"
FLAGS                           = "Flags"
FALSE                           = "False"
TRUE                            = "True"
YES                             = "yes"
NO                              = "no"

XML_TAG_PROJECT                 = "glade-interface"
XML_TAG_REQUIRES                = "requires"
XML_TAG_LIB                     = "lib"
XML_TAG_PREFIX                  = "prefix"
XML_TAG_WIDGET                  = "widget"
XML_TAG_OBJECT                  = "object"
XML_TAG_PROPERTY                = "property"
XML_TAG_CLASS                   = "class"
XML_TAG_ID                      = "id"
XML_TAG_SIGNAL                  = "signal"
XML_TAG_HANDLER                 = "handler"
XML_TAG_NAME                    = "name"
XML_TAG_CHILD                   = "child"
XML_TAG_AFTER                   = "after"
XML_TAG_PACKING                 = "packing"
XML_TAG_PLACEHOLDER             = "placeholder"
XML_TAG_INTERNAL_CHILD          = "internal-child"
XML_TAG_UI_MANAGER              = "UIManager"
XML_TAG_ACTION_GROUP            = "ActionGroup"
XML_TAG_ACTION                  = "Action"
XML_TAG_UI                      = "ui"
XML_TAG_TRANSLATABLE            = "translatable"
XML_TAG_COMMENT                 = "comment"
XML_TAG_CONTEXT                 = "context"
XML_TAG_FILENAME                = "filename"

XML_TAG_ENGINEERING_ENGLISH     = "engineering_english"

