#! /bin/sh

set -e

cp /etc/apt/sources.list /etc/apt/sources.list.testrepo-bak
echo "deb file:///media/mmc1/testrepo old main" >/etc/apt/sources.list
echo "#deb file:///media/mmc1/testrepo new main" >>/etc/apt/sources.list

apt-key add - <<-HERE
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1.4.2 (GNU/Linux)

mQGhBEN8phcRBADgbiTg4UCGbiiM+6dlt3lK8SJsuyPNEqFSL8EzSDCZKUlgEN2o
RfItCxhbxMexXzai/QNP9u3MFsa/aoo2AtSfPF42aUWFcGzrjpmDO+xunkmcc7AD
+jPjYUXHYtdVujwDGxhC2APEvptu2Th3za6Y53639Q9GxHI241eLjD2I7wCglKtk
s+ueE2eTiedPxB2q88dot+0D/2ie7c0qBhyo0U7IyZ8wNU2HfMnMvSea9uckBLjX
ywIpkgAZDV6jImgyO5ohudgCckP9yl974D0MlQ6rbctL46EOfgrcY3EyaO1Tnt19
1XfiOEM9chNF8jSYv+wpjRy6Tp8TlxM0pCZIQuEVdojqp2b8HKgl48HyoLDzFUBl
L2M8A/jf3rnaSNLyJAHpE9aaStVzZ46tIhtUvhawyKUuiHdYbL3b5MezjECstzzW
ghwhkJkDEST/mxQ183WW3H3MABcG9vwK2jt9NNUmX9F0oPa8WPrmgFRcWxAEVZjN
xPTn3QlATwyazvN5t8bJI5/CbPU/h9Q8DSwbPpF48ZvnXHsZtFBFeHBlcmltZW50
YWwgLmRlYiBzaWduaW5nIGtleSAoRG9uJ3QgdHJ1c3QgdGhpcyBrZXkuKSA8bWFy
aXVzLnZvbGxtZXJAbm9raWEuY29tPohgBBMRAgAgBQJDfKYXAhsDBgsJCAcDAgQV
AggDBBYCAwECHgECF4AACgkQTBOVNDJnB3xC9wCgghxq8KBBueIDdryeog8h0VnX
VqwAniXW8VZzcyfh+FcjGkPEWoReI/c+
=dHYi
-----END PGP PUBLIC KEY BLOCK-----
HERE

exit 0
