.\"     Title: apt\-get
.\"    Author: Jason Gunthorpe
.\" Generator: DocBook XSL Stylesheets v1.71.0 <http://docbook.sf.net/>
.\"      Date: 29 Février 2004
.\"    Manual: 
.\"    Source: Linux
.\"
.TH "APT\-GET" "8" "29 Février 2004" "Linux" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NOM"
apt\-get \- Utilitaire d'APT pour la manipulation de paquets \-\- interface en ligne de commande.
.SH "SYNOPSIS"
.HP 8
\fBapt\-get\fR [\fB\-hvs\fR] [\fB\-o=\fR\fB\fIoption\ de\ configuration\fR\fR] [\fB\-c=\fR\fB\fIfichier\fR\fR] {[update] | [upgrade] | [dselect\-upgrade] | [install\ \fIpaquet\fR...] | [remove\ \fIpaquet\fR...] | [source\ \fIpaquet\fR...] | [build\-dep\ \fIpaquet\fR...] | [check] | [clean] | [autoclean]}
.SH "DESCRIPTION"
.PP

\fBApt\-get\fR
est l'outil en ligne de commande pour manipuler les paquets. Il peut être considéré par l'utilisateur comme un générateur de sortie pour les autres outils de la bibliothèque APT. Plusieurs interfaces utilisateur existent, comme dselect, aptitude, synaptic, gnome\-apt ou wajig.
.PP
À moins que l'option
\fB\-h\fR, ou
\fB\-\-help\fR
ne soit donnée, l'une des commandes suivantes doit être présente.
.PP
update
.RS 3n
La commande
update
permet de resynchroniser un fichier répertoriant les paquets disponibles et sa source. Ces fichiers sont récupérés aux endroits spécifiés dans
\fI/etc/apt/sources.list\fR. Ainsi, lorsqu'on utilise une archive Debian, cette commande récupère les fichiers
\fIPackages.gz\fR
et les analyse de manière à rendre disponibles les informations concernant les nouveaux paquets et les paquets mis à jour. On doit toujours exécuter une commande
update
avant les commandes
upgrade
ou
dist\-upgrade. Il faut savoir que l'indicateur de progression d'ensemble n'est pas correct puisque la taille de ces fichiers ne peut être connue à l'avance.
.RE
.PP
upgrade
.RS 3n
La commande
upgrade
permet d'installer les versions les plus récentes de tous les paquets présents sur le système en utilisant les sources énumérées dans
\fI/etc/apt/sources.list\fR. Les paquets installés dont il existe de nouvelles versions sont récupérés et mis à niveau. En aucun cas des paquets déjà installés ne sont supprimés\ ; de même, des paquets qui ne sont pas déjà installés ne sont ni récupérés ni installés. Les paquets dont de nouvelles versions ne peuvent pas être installées sans changer le statut d'installation d'un autre paquet sont laissés dans leur version courante. On doit d'abord exécuter la commande
update
pour que
\fBapt\-get\fR
connaisse l'existence de nouvelles versions des paquets.
.RE
.PP
dselect\-upgrade
.RS 3n

dselect\-upgrade
est utilisée conjointement avec
\fBdselect\fR(8), l'interface traditionnelle Debian pour la gestion des paquets. La commande
dselect\-upgrade
suit les modifications faites par
\fBdselect\fR(8)
dans le champ
Status
des paquets disponibles, et effectue les actions nécessaires à la réalisation de cet état (par exemple, suppression d'anciens paquets, installation de nouveaux paquets).
.RE
.PP
dist\-upgrade
.RS 3n
La commande
dist\-upgrade
effectue la fonction
upgrade
en y ajoutant une gestion intelligente des changements de dépendances dans les nouvelles versions des paquets\ ;
\fBapt\-get\fR
possède un système \(Fo\ intelligent\ \(Fc de résolution des conflits et il essaye, quand c'est nécessaire, de mettre à niveau les paquets les plus importants aux dépens des paquets les moins importants. Le fichier
\fI/etc/apt/sources.list\fR
contient une liste de sources où récupérer les paquets désirés. Voyez aussi
\fBapt_preferences\fR(5)
pour un mécanisme de remplacement des paramètres généraux pour certains paquets.
.RE
.PP
install
.RS 3n
La commande
install
est suivie par un ou plusieurs paquets à installer. Chaque paquet est un nom de paquet\ ; ce n'est pas un nom de fichier entièrement défini (par exemple, dans un système Debian GNU/Linux, on indiquera libc6 et non pas
libc6_1.9.6\-2.deb). Tous les paquets requis par le(s) paquet(s) que l'on veut installer sont aussi récupérés et installés. On se sert du fichier
\fI/etc/apt/sources.list\fR
pour localiser les paquets désirés. Quand un trait d'union est accolé (sans espace intermédiaire) au nom d'un paquet déjà installé, ce paquet est supprimé. De même on peut ajouter un signe \(Fo\ +\ \(Fc pour désigner un paquet à installer. Cette dernière fonctionnalité peut être utilisée pour annuler les décisions prises par le système de résolution des conflits d'apt\-get.
.sp
On peut choisir d'installer une version particulière d'un paquet en faisant suivre son nom par un signe égal et par la version. Cette version sera localisée et l'installation sera demandée. On peut aussi choisir une distribution particulière en faisant suivre le nom du paquet par une barre oblique et par le nom de la distribution ou de l'archive (stable, testing, unstable).
.sp
Avec ces possibilités de choisir la version, de vieilles versions d'un paquet peuvent être installées. Il faut faire attention.
.sp
Enfin, le mécanisme d'\fBapt_preferences\fR(5)
permet de créer d'autres règles pour l'installation des paquets.
.sp
Quand aucun paquet ne correspond à l'expression donnée en argument et que cette expression contient l'un des caractères \(Fo\ .\ \(Fc, \(Fo\ ?\ \(Fc ou \(Fo\ *\ \(Fc, on considère que c'est une expression rationnelle POSIX et elle est appliquée à tous les paquets de la base de données. Tout paquet correspondant est installé (ou supprimé). Notez que la comparaison est effectuée par sous\-chaîne et \(Fo\ lo\ \(Fc correspond aussi bien à \(Fo\ how\-lo\ \(Fc qu'à \(Fo\ lowest\ \(Fc. Si vous ne le voulez pas, ancrez l'expression par un caractère \(Fo\ ^\ \(Fc ou un caractère \(Fo\ $\ \(Fc, ou bien créez une expression plus précise.
.RE
.PP
remove
.RS 3n
La commande
remove
est identique à la commande
install\ ; Mais les paquets sont supprimés et non pas installés. Quand un signe plus est accolé (sans espace intermédiaire) au nom du paquet, le paquet est installé au lieu d'être supprimé.
.RE
.PP
source
.RS 3n
Avec la commande
source,
\fBapt\-get\fR
récupère des paquets sources. APT examine les paquets disponibles pour choisir le paquet source à récupérer. Il trouve ensuite et télécharge dans le répertoire courant la version la plus récente. Les paquets source sont gérés indépendamment des paquets binaires, via les lignes de type
deb\-src
dans le fichier
\fBsources.list\fR(5). On n'obtiendra probablement pas les mêmes sources que celles du paquet installé ou celles du paquet qu'on pourrait installer. Si l'option
\fB\-\-compile\fR
est spécifiée, le paquet est compilé en un binaire .deb avec
\fBdpkg\-buildpackage\fR. Si
\fB\-\-download\-only\fR
est spécifié, le source n'est pas décompacté.
.sp
De la même façon qu'avec les paquets binaires, on peut récupérer une version particulière d'un paquet source en faisant suivre son nom par un signe égal et par la version. Cela permet une comparaison exacte entre le nom du paquet source et la version\ ; cela lance implicitement la commande
APT::Get::Only\-Source.
.sp
Notez que les paquets sources ne sont pas suivis comme le sont les paquets binaires. Ils ne sont présents que dans le répertoire courant et sont semblables à des sources téléchargés sous forme de tarball.
.RE
.PP
build\-dep
.RS 3n
Avec la commande
build\-dep, apt\-get installe ou supprime des paquets dans le but de satisfaire les dépendances de construction d'un paquet source. Pour l'instant, dans la cas d'un paquet virtuel, un paquet est choisi au hasard.
.RE
.PP
check
.RS 3n
La commande
check
est un outil de diagnostic\ ; il met à jour le cache des paquets et cherche des dépendances défectueuses.
.RE
.PP
clean
.RS 3n
La commande
clean
nettoie le référentiel local des paquets récupérés. Il supprime tout, excepté le fichier lock situé dans
\fI/var/cache/apt/archives/\fR
et
\fI/var/cache/apt/archives/partial/\fR. Quand APT est utilisé comme mode de
\fBdselect\fR(8),
clean
est effectué automatiquement. Quand on n'utilise pas dselect, il faut exécuter
apt\-get clean
de temps en temps si l'on veut libérer de l'espace disque.
.RE
.PP
autoclean
.RS 3n
Tout comme
clean,
autoclean
nettoie le référentiel local des paquets récupérés. La différence est qu'il supprime uniquement les paquets qui ne peuvent plus être téléchargés et qui sont grandement inutiles. On peut ainsi contrôler la taille de ce cache sur une longue période. Tant qu'elle n'est pas activée, l'option de configuration
APT::Clean\-Installed
empêche la suppression de paquets installés.
.RE
.SH "OPTIONS"
.PP
Toutes les options en ligne de commande peuvent être positionnées via le fichier de configuration\ ; les descriptifs indiquent l'option de configuration à positionner. En ce qui concerne les options booléennes, on peut annuler le fichier de configuration en utilisant quelque chose comme
\fB\-f\-\fR,\fB\-\-no\-f\fR,
\fB\-f=no\fR
ou d'autres variantes.
.PP
\fB\-d\fR, \fB\-\-download\-only\fR
.RS 3n
Récupération seule\ ; les paquets sont récupérés mais ne sont ni dépaquetés ni installés. Élément de configuration\ :
APT::Get::Download\-Only.
.RE
.PP
\fB\-f\fR, \fB\-\-fix\-broken\fR
.RS 3n
Correction\ ; essaye de réparer un système dont les dépendances sont défectueuses. Cette option, utilisée avec install ou remove, peut omettre tout paquet de façon à permettre à APT de déduire une solution viable. Chaque paquet spécifié doit complètement corriger le problème. Cette option est quelquefois nécessaire lorsque l'on exécute APT pour la première fois\ ; APT lui\-même interdit les dépendances défectueuses dans un système. Il est possible que la structure de dépendances d'un système soit tellement corrompue qu'elle requiert une intervention manuelle (ce qui veut dire la plupart du temps utiliser
\fBdselect\fR(8)
ou
\fBdpkg \-\-remove\fR
pour éliminer les paquets en cause). L'utilisation de cette option conjointement avec
\fB\-m\fR
peut produire une erreur dans certaines situations. Élément de configuration\ :
APT::Get::Fix\-Broken.
.RE
.PP
\fB\-m\fR, \fB\-\-ignore\-missing\fR, \fB\-\-fix\-missing\fR
.RS 3n
Ignorer les paquets manquants\ ; si des paquets ne peuvent être récupérés, ou, après récupération, ne satisfont pas au contrôle d'intégrité, cette commande met ces paquets de côté et gère le résultat. Utiliser cette option conjointement avec
\fB\-f\fR
peut produire une erreur dans certaines situations. Quand un paquet, sélectionné pour une installation (particulièrement si c'est mentionné en ligne de commande), ne peut être récupéré, il est mis silencieusement de côté. Élément de configuration\ :
APT::Get::Fix\-Missing.
.RE
.PP
\fB\-\-no\-download\fR
.RS 3n
Pas de récupération. Le mieux est d'utiliser cette option avec
\fB\-\-ignore\-missing\fR
pour forcer APT à n'utiliser que les .deb qu'il a déjà récupérés. Élément de configuration\ :
APT::Get::Download.
.RE
.PP
\fB\-q\fR, \fB\-\-quiet\fR
.RS 3n
Mode silencieux\ ; cette commande produit une sortie destinée à l'enregistrement dans un fichier\-journal en omettant les indicateurs de progression. Un plus grand nombre de \(Fo\ q\ \(Fc (2 au plus) produit un plus grand silence. On peut aussi utiliser
\fB\-q=#\fR
pour positionner le niveau de silence, et annuler le fichier de configuration. Notez qu'un niveau de silence égal à 2 implique
\fB\-y\fR
et vous ne devez jamais utiliser
\fB\-qq\fR
sans l'accompagner d'un modificateur tel que
\fB\-d\fR,
\fB\-\-print\-uris\fR
ou
\fB\-s\fR\ : APT pourrait exécuter des actions inattendues\ ! Élément de configuration\ :
quiet.
.RE
.PP
\fB\-s\fR, \fB\-\-simulate\fR, \fB\-\-just\-print\fR, \fB\-\-dry\-run\fR, \fB\-\-recon\fR, \fB\-\-no\-act\fR
.RS 3n
Simulation\ ; cette commande réalise une simulation des actions qui seraient exécutées mais ne modifie pas le système. Élément de configuration\ :
APT::Get::Simulate.
.sp
La simulation affiche une série de lignes représentant chacune une opération de dpkg, Configure (Conf),Remove (Remv),Unpack (Inst). Les crochets encadrent des paquets endommagés et des crochets n'encadrant rien indiquent que les dommages n'ont aucune conséquence (rare).
.RE
.PP
\fB\-y\fR, \fB\-\-yes\fR, \fB\-\-assume\-yes\fR
.RS 3n
Répond automatiquement oui aux questions\ ; présume \(Fo\ oui\ \(Fc comme réponse à toutes les questions et s'exécute de manière non interactive. Dans le cas d'une situation indésirable, comme le changement d'un paquet gelé, l'installation d'un paquet non authentifié ou la suppression d'un paquet essentiel,
apt\-get
s'interrompt. Élément de configuration\ :
APT::Get::Assume\-Yes.
.RE
.PP
\fB\-u\fR, \fB\-\-show\-upgraded\fR
.RS 3n
Afficher les paquets mis à niveau\ ; affiche une liste de tous les paquets à mettre à niveau. Élément de configuration\ :
APT::Get::Show\-Upgraded.
.RE
.PP
\fB\-V\fR, \fB\-\-verbose\-versions\fR
.RS 3n
Afficher les versions complètes des paquets installés ou mis à niveau. Élément de configuration\ :
APT::Get::Show\-Versions.
.RE
.PP
\fB\-b\fR, \fB\-\-compile\fR, \fB\-\-build\fR
.RS 3n
Cette commande compile un paquet source après l'avoir récupéré. Élément de configuration\ :
APT::Get::Compile.
.RE
.PP
\fB\-\-ignore\-hold\fR
.RS 3n
Cette commande ignore la marque \(Fo\ Hold\ \(Fc d'un paquet\ ; par ce biais,
\fBapt\-get\fR
ignore un \(Fo\ hold\ \(Fc placé sur un paquet. cela peut être utile avec
dist\-upgrade
pour annuler un grand nombre de \(Fo\ hold\ \(Fc indésirables. Élément de configuration\ :
APT::Ignore\-Hold.
.RE
.PP
\fB\-\-no\-upgrade\fR
.RS 3n
Aucune mise à niveau\ ; quand elle est utilisée avec
install, cette commande empêche les paquets listés sur la ligne de commande d'être mis à niveau. Élément de configuration\ :
APT::Get::Upgrade.
.RE
.PP
\fB\-\-force\-yes\fR
.RS 3n
Forcer l'acceptation\ ; cette option est dangereuse parce qu'elle laisse APT continuer sans poser de questions quand il réalise quelque chose de potentiellement dommageable. Cette option ne doit être utilisée que dans des circonstances très spéciales. Utiliser
force\-yes
peut détruire le système\ ! Élément de configuration\ :
APT::Get::force\-yes.
.RE
.PP
\fB\-\-print\-uris\fR
.RS 3n
Au lieu d'aller chercher les paquets à installer, leurs URI sont affichées. Chaque URI a un chemin, un nom de fichier destination, une taille et une clé md5 attendue. Notez que le nom de fichier à afficher ne correspond pas toujours au nom de fichier sur le site distant\ ! Cette option fonctionne aussi avec la commande
source
et avec la commande
update. Avec la commande
update, la somme MD5 et la taille ne sont pas données et c'est à l'utilisateur de décompresser les fichiers compressés. Élément de configuration\ :
APT::Get::Print\-URIs.
.RE
.PP
\fB\-\-purge\fR
.RS 3n
Utiliser purge à la place de remove pour supprimer tout ce qui peut être supprimé. Un astérisque (*) sera affiché près des paquets qui vont être purgés. Élément de configuration\ :
APT::Get::Purge.
.RE
.PP
\fB\-\-reinstall\fR
.RS 3n
Réinstaller les paquets déjà installés avec leur version la plus récente. Élément de configuration\ :
APT::Get::ReInstall.
.RE
.PP
\fB\-\-list\-cleanup\fR
.RS 3n
Cette option est activée par défaut\ ; utilisez
\-\-no\-list\-cleanup
pour la désactiver. Quand elle est activée,
\fBapt\-get\fR
gère automatiquement le contenu de
\fI/var/lib/apt/lists\fR
afin d'assurer que les fichiers obsolètes soient effacés. La seule raison de la désactiver est une modification fréquente de votre liste de sources. Élément de configuration\ :
APT::Get::List\-Cleanup.
.RE
.PP
\fB\-t\fR, \fB\-\-target\-release\fR, \fB\-\-default\-release\fR
.RS 3n
Cette option contrôle l'entrée par défaut pour les questions de distribution\ ; une étiquette (pin) par défaut dont la priorité vaut 990 est créé en utilisant la chaîne spécifiée. Le fichier des préférences peut annuler cette décision. En clair, cette option permet de contrôler simplement dans quelle distribution seront récupérés les paquets. Par exemple\ :
\fB\-t '2.1*'\fR
ou
\fB\-t unstable\fR. Élément de configuration\ :
APT::Default\-Release. Voyez aussi la page de manuel d'\fBapt_preferences\fR(5).
.RE
.PP
\fB\-\-trivial\-only\fR
.RS 3n
Ne réalise que les opérations \(Fo\ triviales\ \(Fc. Logiquement ceci peut être considéré comme relatif à
\fB\-\-assume\-yes\fR. Alors que
\fB\-\-assume\-yes\fR
répond oui à n'importe quelle question,
\fB\-\-trivial\-only\fR
répond non. Élément de configuration\ :
APT::Get::Trivial\-Only.
.RE
.PP
\fB\-\-no\-remove\fR
.RS 3n
Quand des paquets doivent être supprimés, apt\-get s'arrête immédiatement sans poser de questions. Élément de configuration\ :
APT::Get::Remove.
.RE
.PP
\fB\-\-only\-source\fR
.RS 3n
Cette option n'a de sens qu'avec les commandes
source
et
build\-dep. Elle indique que les noms de sources donnés ne doivent pas être repérés à travers le tableau des binaires. Cela signifie que si cette option est choisie, la commande
source
acceptera seulement des noms de paquets source comme argument\ ; elle n'acceptera pas de les rechercher à partir des noms de paquets binaires correspondants. Élément de configuration\ :
APT::Get::Only\-Source
.RE
.PP
\fB\-\-diff\-only\fR, \fB\-\-tar\-only\fR
.RS 3n
Ne récupérer que le fichier diff ou tar d'une archive de source. Élément de configuration\ :
APT::Get::Diff\-Only
et
APT::Get::Tar\-Only.
.RE
.PP
\fB\-\-arch\-only\fR
.RS 3n
Ne traiter que les dépendances de construction pour telle architecture. Élément de configuration\ :
APT::Get::Arch\-Only
.RE
.PP
\fB\-\-allow\-unauthenticated\fR
.RS 3n
Ignorer le fait que les paquets ne peuvent pas être authentifiés ; pas d'interrogation de l'utilisateur. C'est très utile pour certains outils comme pbuilder Élément de configuration\ :
APT::Get::AllowUnauthenticated.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 3n
Affiche un mode d'emploi succinct.
.RE
.PP
\fB\-v\fR, \fB\-\-version\fR
.RS 3n
Affiche la version du programme.
.RE
.PP
\fB\-c\fR, \fB\-\-config\-file\fR
.RS 3n
Fichier de configuration\ ; indique quel fichier de configuration utiliser. Le programme lit le fichier de configuration par défaut, puis celui\-ci. Voyez
\fBapt.conf\fR(5)
pour la syntaxe.
.RE
.PP
\fB\-o\fR, \fB\-\-option\fR
.RS 3n
Donne une option de configuration\ ; cela fixe une option de configuration arbitraire. La syntaxe est :
\fB\-o Foo::Bar=bar\fR.
.RE
.SH "FICHIERS"
.PP
\fI/etc/apt/sources.list\fR
.RS 3n
Liste les emplacements où aller chercher les paquets. Élément de configuration\ :
Dir::Etc::SourceList.
.RE
.PP
\fI/etc/apt/apt.conf\fR
.RS 3n
Fichier de configuration d'APT. Élément de configuration\ :
Dir::Etc::Main.
.RE
.PP
\fI/etc/apt/apt.conf.d/\fR
.RS 3n
Éléments du fichier de configuration d'APT. Élément de configuration\ :
Dir::Etc::Parts.
.RE
.PP
\fI/etc/apt/preferences\fR
.RS 3n
Fichier des préférences. C'est dans ce fichier qu'on peut faire de l'étiquetage (pinning) c'est\-à\-dire, choisir d'obtenir des paquets d'une source distincte ou d'une distribution différente. Élément de configuration\ :
Dir::Etc::Preferences.
.RE
.PP
\fI/var/cache/apt/archives/\fR
.RS 3n
Zone de stockage pour les paquets récupérés. Élément de configuration\ :
Dir::Cache::Archives.
.RE
.PP
\fI/var/cache/apt/archives/partial/\fR
.RS 3n
Zone de stockage pour les paquets en transit. Élément de configuration\ :
Dir::Cache::Archives
(implicitement, partial).
.RE
.PP
\fI/var/lib/apt/lists/\fR
.RS 3n
Zone de stockage des informations concernant chaque ressource spécifiée dans
\fBsources.list\fR(5). Élément de configuration\ :
Dir::State::Lists.
.RE
.PP
\fI/var/lib/apt/lists/partial/\fR
.RS 3n
Zone de stockage pour les informations d'état des paquets en transit. Élément de configuration\ :
Dir::State::Lists
(implicit partial).
.RE
.SH "VOIR AUSSI"
.PP

\fBapt\-cache\fR(8),
\fBapt\-cdrom\fR(8),
\fBdpkg\fR(8),
\fBdselect\fR(8),
\fBsources.list\fR(5),
\fBapt.conf\fR(5),
\fBapt\-config\fR(8), le guide \(Fo\ APT users guide\ \(Fc dans /usr/share/doc/apt/,
\fBapt_preferences\fR(5), le guide APT.
.SH "DIAGNOSTIC"
.PP
\fBapt\-get\fR
renvoie zéro après une opération normale, le décimal 100 en cas d'erreur.
.SH "BOGUES"
.PP
Voyez la
[1]\&\fI page concernant les bogues d'APT\fR. Si vous voulez signaler un bogue, consultez le texte
\fI/usr/share/doc/debian/bug\-reporting.txt\fR
ou utilisez la commande
\fBreportbug\fR(1).
.SH "TRADUCTION"
.PP
Jérôme Marant. 2000\ ; mise à jour : Philippe Batailler. 2005.
<debian\-l10n\-french@lists.debian.org>.
.SH "AUTHORS"
.PP
\fBJason Gunthorpe\fR
.sp -1n
.IP "" 3n
Auteur.
.PP
\fBAPT team\fR
.sp -1n
.IP "" 3n
Auteur.
.SH "REFERENCES"
.TP 3
1.\ page concernant les bogues d'APT
\%http://bugs.debian.org/src:apt
