.\"     Title: apt\-key
.\"    Author: Jason Gunthorpe
.\" Generator: DocBook XSL Stylesheets v1.71.0 <http://docbook.sf.net/>
.\"      Date: 14 décembre 2003
.\"    Manual: 
.\"    Source: Linux
.\"
.TH "APT\-KEY" "8" "14 décembre 2003" "Linux" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NOM"
apt\-key \- Utilitaire de gestion des clés
.SH "SYNOPSIS"
.HP 8
\fBapt\-key\fR [\fIcommand\fR/] [\fB\fIarguments\fR\fR...]
.SH "DESCRIPTION"
.PP

\fBapt\-key\fR
gère les clés dont se sert apt pour authentifier les paquets. Les paquets authentifiés par ces clés seront réputés fiables.
.SH "COMMANDES"
.PP
add \fIfichier\fR
.RS 3n
Ajouter une clé à la liste des clés fiables. La clé est lue dans
\fIfichier\fR, ou sur l'entrée standard si
\fIfichier\fR
est
\-.
.RE
.PP
del \fIkeyid\fR
.RS 3n
Supprimer une clé de la liste des clés fiables.
.RE
.PP
list
.RS 3n
Afficher la liste des clés fiables.
.RE
.PP
update
.RS 3n
Mettre à jour le trousseau de clés local avec le trousseau de clés de l'archive Debian et supprimer les clés qui sont périmées.
.RE
.SH "FICHIERS"
.PP
\fI/etc/apt/trusted.gpg\fR
.RS 3n
Trousseau de clés locales fiables, les nouvelles clés sont ajoutées ici.
.RE
.PP
\fI/etc/apt/trustdb.gpg\fR
.RS 3n
Base de données locale fiable des clés de l'archive.
.RE
.PP
\fI/usr/share/keyrings/debian\-archive\-keyring.gpg\fR
.RS 3n
Trousseau des clés fiables de l'archive Debian.
.RE
.PP
\fI/usr/share/keyrings/debian\-archive\-removed\-keys.gpg\fR
.RS 3n
Trousseau des clés fiables supprimées de l'archive Debian.
.RE
.SH "VOIR AUSSI"
.PP

\fBapt\-get\fR(8),
\fBapt\-secure\fR(8)
.SH "BOGUES"
.PP
Voyez la
[1]\&\fI page concernant les bogues d'APT\fR. Si vous voulez signaler un bogue, consultez le texte
\fI/usr/share/doc/debian/bug\-reporting.txt\fR
ou utilisez la commande
\fBreportbug\fR(1).
.SH "AUTEUR"
.PP
APT a été écrit par l'équipe APT
<apt@packages.debian.org>.
.SH "TRADUCTION"
.PP
Philippe Batailler.
<debian\-l10n\-french@lists.debian.org>. 2005.
.SH "AUTEUR"
.PP
\fBJason Gunthorpe\fR
.sp -1n
.IP "" 3n
Auteur.
.SH "COPYRIGHT"
Copyright \(co 1998\-2001 Jason Gunthorpe
.br
.SH "REFERENCES"
.TP 3
1.\ page concernant les bogues d'APT
\%http://bugs.debian.org/src:apt
