.\"     Title: apt\-cdrom
.\"    Author: Jason Gunthorpe
.\" Generator: DocBook XSL Stylesheets v1.71.0 <http://docbook.sf.net/>
.\"      Date: 14 Février 2004
.\"    Manual: 
.\"    Source: Linux
.\"
.TH "APT\-CDROM" "8" "14 Février 2004" "Linux" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NOM"
apt\-cdrom \- Gestion des cédéroms par APT
.SH "SYNOPSIS"
.HP 10
\fBapt\-cdrom\fR [\fB\-hvrmfan\fR] [\fB\-d=\fR\fB\fIpoint\ de\ montage\ du\ cédérom\fR\fR] [\fB\-o=\fR\fB\fIoption\ de\ configuration\fR\fR] [\fB\-c=\fR\fB\fIfichier\fR\fR] [[add] | [ident]]
.SH "DESCRIPTION"
.PP

\fBapt\-cdrom\fR
est utilisé pour ajouter un nouveau cédérom à la liste des sources disponibles.
\fBapt\-cdrom\fR
prend soin de déterminer la structure du disque, de corriger de possibles erreurs de gravure et de vérifier les fichiers d'index.
.PP
Il est nécessaire d'utiliser
\fBapt\-cdrom\fR
pour ajouter des cédéroms au système APT, cela ne peut être réalisé \(Fo\ à la main\ \(Fc. Par ailleurs, chaque disque d'un ensemble de cédéroms doit être séparément inséré et parcouru pour prendre en compte de possibles erreurs de gravure.
.PP
À moins que l'option
\fB\-h\fR
ou
\fB\-\-help\fR
ne soit donnée, l'une des commandes suivantes doit être présente.
.PP
add
.RS 3n
La commande
add
est utilisée pour ajouter un nouveau disque à la liste des sources. Elle démonte le cédérom, réclame l'insertion d'un disque, parcourt ensuite le disque et copie les fichiers d'index. Si le disque ne possède pas de répertoire
\fIdisk/\fR
correct, un titre descriptif est demandé.
.sp
APT utilise un identifiant de cédérom pour reconnaître le disque qui se trouve actuellement dans le lecteur et maintient une base de données de ces identifiants dans
\fI/var/lib/apt/cdroms.list\fR.
.RE
.PP
ident
.RS 3n
Un outil de débogage pour rapporter l'identifiant du disque actuel ainsi que le nom du fichier stocké.
.RE
.SH "OPTIONS"
.PP
Toutes les options en ligne de commande peuvent être positionnées via le fichier de configuration\ ; les descriptifs indiquent l'option de configuration à positionner. En ce qui concerne les options booléennes, on peut annuler le fichier de configuration en utilisant quelque chose comme
\fB\-f\-\fR,\fB\-\-no\-f\fR,
\fB\-f=no\fR
ou d'autres variantes.
.PP
\fB\-d\fR, \fB\-\-cdrom\fR
.RS 3n
Point de montage\ ; spécifie l'emplacement de montage du cédérom. Ce point de montage doit être spécifié dans
\fI/etc/fstab\fR
et correctement configuré. Élément de configuration\ :
Acquire::cdrom::mount.
.RE
.PP
\fB\-r\fR, \fB\-\-rename\fR
.RS 3n
Change le nom d'un disque\ ; change le nom d'un disque ou annule le nom donné aux disques. Cette option oblige
\fBapt\-cdrom\fR
à demander un nouveau nom à l'utilisateur. Élément de configuration\ :
APT::CDROM::Rename.
.RE
.PP
\fB\-m\fR, \fB\-\-no\-mount\fR
.RS 3n
Pas de montage\ ; empêche
\fBapt\-cdrom\fR
de monter ou démonter le point de montage. Élément de configuration\ :
APT::CDROM::NoMount.
.RE
.PP
\fB\-f\fR, \fB\-\-fast\fR
.RS 3n
Copie rapide\ ; suppose que les paquets sont valides et ne vérifie pas chaque paquet. Cette option ne devrait être utilisée que si
\fBapt\-cdrom\fR
a préalablement utilisé ce disque et n'a trouvé aucune erreur. Élément de configuration\ :
APT::CDROM::Fast.
.RE
.PP
\fB\-a\fR, \fB\-\-thorough\fR
.RS 3n
Parcours minutieux des paquets\ ; cette option peut être nécessaire avec de vieux cédéroms de systèmes Debian 1.1 ou 1.2 dont les fichiers Packages sont situés dans des endroits étranges. Il faudra plus de temps pour parcourir le CD mais tous les paquets seront repérés.
.RE
.PP
\fB\-n\fR, \fB\-\-just\-print\fR, \fB\-\-recon\fR, \fB\-\-no\-act\fR
.RS 3n
Aucune modification\ ; ne pas modifier le fichier
\fBsources.list\fR(5)ni les fichiers d'index. Cependant, tout est vérifié. Élément de configuration\ :
APT::CDROM::NoAct.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 3n
Affiche un mode d'emploi succinct.
.RE
.PP
\fB\-v\fR, \fB\-\-version\fR
.RS 3n
Affiche la version du programme.
.RE
.PP
\fB\-c\fR, \fB\-\-config\-file\fR
.RS 3n
Fichier de configuration\ ; indique quel fichier de configuration utiliser. Le programme lit le fichier de configuration par défaut, puis celui\-ci. Voyez
\fBapt.conf\fR(5)
pour la syntaxe.
.RE
.PP
\fB\-o\fR, \fB\-\-option\fR
.RS 3n
Donne une option de configuration\ ; cela fixe une option de configuration arbitraire. La syntaxe est :
\fB\-o Foo::Bar=bar\fR.
.RE
.SH "VOIR AUSSI"
.PP

\fBapt.conf\fR(5),
\fBapt\-get\fR(8),
\fBsources.list\fR(5).
.SH "DIAGNOSTICS"
.PP
\fBapt\-cdrom\fR
retourne zéro après un déroulement normal, et le nombre décimal 100 en cas d'erreur.
.SH "BOGUES"
.PP
Voyez la
[1]\&\fI page concernant les bogues d'APT\fR. Si vous voulez signaler un bogue, consultez le texte
\fI/usr/share/doc/debian/bug\-reporting.txt\fR
ou utilisez la commande
\fBreportbug\fR(1).
.SH "TRADUCTION"
.PP
Jérôme Marant. 2000\ ; mise à jour : Philippe Batailler. 2005.
<debian\-l10n\-french@lists.debian.org>.
.SH "AUTHORS"
.PP
\fBJason Gunthorpe\fR
.sp -1n
.IP "" 3n
Auteur.
.PP
\fBAPT team\fR
.sp -1n
.IP "" 3n
Auteur.
.SH "REFERENCES"
.TP 3
1.\ page concernant les bogues d'APT
\%http://bugs.debian.org/src:apt
