.\"     Title: apt\-sortpkgs
.\"    Author: Jason Gunthorpe
.\" Generator: DocBook XSL Stylesheets v1.71.0 <http://docbook.sf.net/>
.\"      Date: 29 February 2004
.\"    Manual: 
.\"    Source: Linux
.\"
.TH "APT\-SORTPKGS" "1" "29 February 2004" "Linux" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NOM"
apt\-sortpkgs \- Un outil pour trier les index de paquets.
.SH "SYNOPSIS"
.HP 13
\fBapt\-sortpkgs\fR [\fB\-hvs\fR] [\fB\-o=\fR\fB\fIoption\ de\ configuration\fR\fR] [\fB\-c=\fR\fB\fIfichier\fR\fR] \fIfichier\fR...
.SH "DESCRIPTION"
.PP

\fBApt\-sortpkgs\fR
prend un index (un index de Source ou un index de paquet) et trie leurs enregistrements selon le nom de paquet. Un tri des champs de chaque enregistrement est réalisé selon des règles internes.
.PP
Le résultat est envoyé sur la sortie standard\ ; l'entrée doit être un fichier analysable.
.SH "OPTIONS"
.PP
Toutes les options en ligne de commande peuvent être positionnées via le fichier de configuration\ ; les descriptifs indiquent l'option de configuration à positionner. En ce qui concerne les options booléennes, on peut annuler le fichier de configuration en utilisant quelque chose comme
\fB\-f\-\fR,\fB\-\-no\-f\fR,
\fB\-f=no\fR
ou d'autres variantes.
.PP
\fB\-s\fR, \fB\-\-source\fR
.RS 3n
Se servir d'un index de sources pour le tri des champs. Élément de configuration\ :
APT::SortPkgs::Source.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 3n
Affiche un mode d'emploi succinct.
.RE
.PP
\fB\-v\fR, \fB\-\-version\fR
.RS 3n
Affiche la version du programme.
.RE
.PP
\fB\-c\fR, \fB\-\-config\-file\fR
.RS 3n
Fichier de configuration\ ; indique quel fichier de configuration utiliser. Le programme lit le fichier de configuration par défaut, puis celui\-ci. Voyez
\fBapt.conf\fR(5)
pour la syntaxe.
.RE
.PP
\fB\-o\fR, \fB\-\-option\fR
.RS 3n
Donne une option de configuration\ ; cela fixe une option de configuration arbitraire. La syntaxe est :
\fB\-o Foo::Bar=bar\fR.
.RE
.SH "VOIR AUSSI"
.PP

\fBapt.conf\fR(5)
.SH "DIAGNOSTICS"
.PP

\fBapt\-sortpkgs\fR
retourne zéro si tout se passe bien ou 100 en cas d'erreur.
.SH "BOGUES"
.PP
Voyez la
[1]\&\fI page concernant les bogues d'APT\fR. Si vous voulez signaler un bogue, consultez le texte
\fI/usr/share/doc/debian/bug\-reporting.txt\fR
ou utilisez la commande
\fBreportbug\fR(1).
.SH "TRADUCTION"
.PP
Philippe Batailler.
<debian\-l10n\-french@lists.debian.org>. 2005.
.SH "AUTHORS"
.PP
\fBJason Gunthorpe\fR
.sp -1n
.IP "" 3n
Auteur.
.PP
\fBAPT team\fR
.sp -1n
.IP "" 3n
Auteur.
.SH "REFERENCES"
.TP 3
1.\ page concernant les bogues d'APT
\%http://bugs.debian.org/src:apt
