#! /bin/sh

if [ "$1" != "do" -o "$2" != "it" ]; then
  exec >&2
  echo
  echo "** This program will erase your MMC and will **"
  echo "**    put the Sardine distribution on it.    **"
  echo
  echo "Run it as \"sardine-installer do it\".  No further"
  echo "questions will be asked, so once again: this program"
  echo "WILL ERASE YOUR MMC."
  echo
  echo "The Sardine distribution will be downloaded and"
  echo "copied to the MMC on the fly.  About 60 MiB will be"
  echo "downloaded, so make sure you are well connected."
  echo
  echo "This preliminary version of the Sardine Installer will"
  echo "download from a temporary location that is only accessible"
  echo "when connected to osso.net WITHOUT using a proxy."
  echo
  echo "This program is quite simple.  Feel free to look at"
  echo "the source and modify it to suit your needs."
  exit 1
fi;

set -e -x

DEV=/dev/mmcblk0p1
ROOTFS="http://10.19.147.124/sardine-rootfs-0.tar.gz"

if cat /proc/mounts | cut -d' ' -f 0 | grep -F -q $DEV; then
  umount $DEV
fi

mke2fs $DEV

if ! grep -q ext2 /proc/filesystems; then
  insmod /mnt/initfs/lib/modules/current/ext2.ko
fi

mount -t ext2 $DEV /media/mmc1
chroot /mnt/initfs wget -O - $ROOTFS | (cd /media/mmc1 && tar xvvzf -)
umount /media/mmc1      # this might take some time...

# chroot /mnt/initfs cal-tool -R mmc
