.\" matchbox-window-manager.1
.\" Copyright 2004  Moray Allan
.TH matchbox-window-manager 1 "Jul 16 2004" ""
.SH NAME
matchbox-window-manager \- window manager for resource-limited systems
.SH SYNOPSIS
.B matchbox-window-manager [options]
.SH OPTIONS
.TP
\fB\-display\fR
<string>
.TP
\fB\-theme\fR
<string>
.TP
\fB\-use_titlebar\fR
<yes|no>
.TP
\fB\-use_cursor\fR
<yes|no>
.TP
\fB\-use_lowlight\fR
<yes|no>
.TP
\fB\-use_dialog_mode\fR
<free|const|const-horiz>
.HP
\fB\-use_desktop_mode\fR <decorated|plain>
.SH DESCRIPTION
.B matchbox-window-manager
is a window manager for the X Window System running on non-desktop
embedded platforms such as handhelds, set-top boxes, kiosks and anything else
for which screen space, input mechanisms or system resources are limited.

.SH AUTHOR
.B matchbox-window-manager
was written by Matthew Allum <mallum@o-hand.com>.

