/* Generated by GOB (v2.0.3)   (do not edit directly) */

#include <glib.h>
#include <glib-object.h>
#ifndef __GNOME_VFS_METADATA_H__
#define __GNOME_VFS_METADATA_H__

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/*
 * Type checking and casting macros
 */
#define GNOME_TYPE_VFS_METADATA	(gnome_vfs_metadata_get_type())
#define GNOME_VFS_METADATA(obj)	G_TYPE_CHECK_INSTANCE_CAST((obj), gnome_vfs_metadata_get_type(), GnomeVfsMetadata)
#define GNOME_VFS_METADATA_CONST(obj)	G_TYPE_CHECK_INSTANCE_CAST((obj), gnome_vfs_metadata_get_type(), GnomeVfsMetadata const)
#define GNOME_VFS_METADATA_CLASS(klass)	G_TYPE_CHECK_CLASS_CAST((klass), gnome_vfs_metadata_get_type(), GnomeVfsMetadataClass)
#define GNOME_IS_VFS_METADATA(obj)	G_TYPE_CHECK_INSTANCE_TYPE((obj), gnome_vfs_metadata_get_type ())

#define GNOME_VFS_METADATA_GET_CLASS(obj)	G_TYPE_INSTANCE_GET_CLASS((obj), gnome_vfs_metadata_get_type(), GnomeVfsMetadataClass)

/* Private structure type */
typedef struct _GnomeVfsMetadataPrivate GnomeVfsMetadataPrivate;

/*
 * Main object structure
 */
#ifndef __TYPEDEF_GNOME_VFS_METADATA__
#define __TYPEDEF_GNOME_VFS_METADATA__
typedef struct _GnomeVfsMetadata GnomeVfsMetadata;
#endif
struct _GnomeVfsMetadata {
	GObject __parent__;
	/*< public >*/
	char * key_file_uri;
	char * metadata_dir_uri;
	/*< private >*/
	GnomeVfsMetadataPrivate *_priv;
};

/*
 * Class definition
 */
typedef struct _GnomeVfsMetadataClass GnomeVfsMetadataClass;
struct _GnomeVfsMetadataClass {
	GObjectClass __parent__;
	char * (* get_string) (GnomeVfsMetadata * self, const char * key);
	void (* set_string) (GnomeVfsMetadata * self, const char * key, const char * value);
	int (* get_int) (GnomeVfsMetadata * self, const char * key);
	void (* set_int) (GnomeVfsMetadata * self, const char * key, gpointer value);
};


/*
 * Public methods
 */
GType	gnome_vfs_metadata_get_type	(void);char * 	gnome_vfs_metadata_get_string	(GnomeVfsMetadata * self,
					const char * key);
void 	gnome_vfs_metadata_set_string	(GnomeVfsMetadata * self,
					const char * key,
					const char * value);
int 	gnome_vfs_metadata_get_int	(GnomeVfsMetadata * self,
					const char * key);
void 	gnome_vfs_metadata_set_int	(GnomeVfsMetadata * self,
					const char * key,
					gpointer value);
GObject * 	gnome_vfs_metadata_new	(const char * uri);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
