/* Generated by GOB (v2.0.3)   (do not edit directly) */

#ifndef __GNOME_VFS_METADATA_PRIVATE_H__
#define __GNOME_VFS_METADATA_PRIVATE_H__

#include "gnome-vfs-metadata.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

struct _GnomeVfsMetadataPrivate {
#line 224 "gnome-vfs-metadata.gob"
	GHashTable * strings;
#line 225 "gnome-vfs-metadata.gob"
	GHashTable * integers;
#line 228 "gnome-vfs-metadata.gob"
	gboolean keys_loaded;
#line 20 "gnome-vfs-metadata-private.h"
};

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
