#! /bin/bash -e
#
# Debian prerm script for Python x.y hierarchical modules
# Written by Gregor Hoffleit <flight@debian.org>
# Extended by Matthias Klose <doko@debian.org>
#

PACKAGE=`basename $0 | sed -e 's/\.[^.]*$//'`
PV=`dpkg --listfiles $PACKAGE | sed -n -e '/^\/usr\/lib\/python.*\//{
  s,/usr/lib/python\([0-9][0-9.]*\)/.*,\1,p
  q
}'`

if [ "$1" != "upgrade" ]; then
	update-alternatives --remove py${PV}gtk.py \
		/usr/lib/python$PV/site-packages/pygtk.py.$PACKAGE
fi

#DEBHELPER#
