#!/bin/sh

# XXX there's gotta be a better way to do this... 
# why doesn't pydoc2.4 -w [path] work?

gendocdir=`dirname $0`
cwd=`pwd`
(
    cd $gendocdir/../build/lib*/ 
    pydoc2.4 -w bluetooth >> /dev/null
    pydoc2.4 -w _bluetooth >> /dev/null
    mv -f bluetooth.html ../../doc/bluetooth.html
    mv -f _bluetooth.html ../../doc/_bluetooth.html
)

echo "documentation written to $gendocdir/bluetooth.html"
