#!/bin/sh -e
if type dpkg-trigger >/dev/null 2>&1 && \
    dpkg-trigger /usr/share/icons/hicolor >/dev/null 2>&1; then
        echo Deferring gtk-update-icon-cache...
        exit 0
fi
echo Doing gtk-update-icon-cache
exec gtk-update-icon-cache-now "$@"
