Document: pybluez
Title: Debian pybluez Manual
Author: <insert document author here>
Abstract: This manual describes what pybluez is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pybluez/pybluez.sgml.gz

Format: postscript
Files: /usr/share/doc/pybluez/pybluez.ps.gz

Format: text
Files: /usr/share/doc/pybluez/pybluez.text.gz

Format: HTML
Index: /usr/share/doc/pybluez/html/index.html
Files: /usr/share/doc/pybluez/html/*.html

  
