Document: app-killer
Title: Debian app-killer Manual
Author: <insert document author here>
Abstract: This manual describes what app-killer is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/app-killer/app-killer.sgml.gz

Format: postscript
Files: /usr/share/doc/app-killer/app-killer.ps.gz

Format: text
Files: /usr/share/doc/app-killer/app-killer.text.gz

Format: HTML
Index: /usr/share/doc/app-killer/html/index.html
Files: /usr/share/doc/app-killer/html/*.html

  
