#!/bin/sh

SERVICEDIR=/usr/lib/dbus-1.0/services
DESTDIR=debian/tmp

if [ -z "$1" ]; then
    echo "Usage: $0 [--destdir=...] <desktop file> [file2...]"
fi

if echo "$1" | grep -q "^--destdir="; then
    DESTDIR=`echo $1 | sed -e 's/^--destdir=//'`
    shift
fi

if [ ! -d "$DESTDIR$SERVICEDIR" ]; then
    mkdir -p "$DESTDIR$SERVICEDIR"
fi

FILE="$1"
while shift; do
    if [ -f "$FILE" ]; then
        cp "$FILE" "$DESTDIR$SERVICEDIR"
    fi
    FILE="$1"
done
