/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.in by autoheader.  */

/* Define to 1 if you have the `bind_textdomain_codeset' function. */
#define HAVE_BIND_TEXTDOMAIN_CODESET 1

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* If Gtk 2.10 was found */
#define HAVE_GTK_2_10 $have_gtk_210

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* whether to include numeric python support */
/* #undef HAVE_NUMPY */

/* Define to 1 if pycairo is available */
/* #undef HAVE_PYCAIRO */

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Name of package */
#define PACKAGE "pygtk"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "http://bugzilla.gnome.org/enter_bug.cgi?product=pygtk"

/* Define to the full name of this package. */
#define PACKAGE_NAME "pygtk"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "pygtk 2.10.3"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "pygtk"

/* Define to the version of this package. */
#define PACKAGE_VERSION "2.10.3"

/* pycairo major version */
/* #undef PYCAIRO_MAJOR_VERSION */

/* pycairo micro version */
/* #undef PYCAIRO_MICRO_VERSION */

/* pycairo minor version */
/* #undef PYCAIRO_MINOR_VERSION */

/* PyGtk major version */
#define PYGTK_MAJOR_VERSION 2

/* PyGtk micro version */
#define PYGTK_MICRO_VERSION 3

/* PyGtk minor version */
#define PYGTK_MINOR_VERSION 10

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Version number of package */
#define VERSION "2.10.3"
